export const ADMIN: Record<string, string> = {
  "Welcome, {name}": "স্বাগতম, {name}",
  "Verify partners, keep food moving and watch the platform’s health.": "অংশীদারদের যাচাই করুন, খাবার চলমান রাখুন এবং প্ল্যাটফর্মের অবস্থা নজরে রাখুন।",
  "Total users": "মোট ব্যবহারকারী",
  "{d} donors · {n} NGOs · {v} volunteers": "{d} দাতা · {n} এনজিও · {v} স্বেচ্ছাসেবক",
  "Pending to delivered": "অপেক্ষমাণ থেকে পৌঁছানো পর্যন্ত",
  "Pending requests": "অপেক্ষমাণ অনুরোধ",
  "Food requests and matches waiting": "অপেক্ষমাণ খাবারের অনুরোধ ও মিল",
  "{n} distributed by NGOs": "এনজিও {n}টি বিতরণ করেছে",
  "Impact": "প্রভাব",
  "Expired (food lost)": "মেয়াদোত্তীর্ণ (নষ্ট খাবার)",
  "{n} cancelled": "{n}টি বাতিল",
  "{a} volunteers available now · {s} suspended or deactivated accounts": "এখন {a} জন স্বেচ্ছাসেবক ফাঁকা · {s}টি স্থগিত বা নিষ্ক্রিয় অ্যাকাউন্ট",
  "Platform activity": "প্ল্যাটফর্মের কার্যক্রম",
  "Food rescued and delivered over time.": "সময়ের সঙ্গে উদ্ধার ও পৌঁছানো খাবার।",
  "Open reports": "রিপোর্ট খুলুন",
  "Food safety": "খাদ্য নিরাপত্তা",
  "Food expiring within the hour, and donations paused for a safety check. Open one to act.": "এক ঘণ্টার মধ্যে মেয়াদ শেষ হবে এমন খাবার এবং নিরাপত্তা যাচাইয়ের জন্য স্থগিত দান। ব্যবস্থা নিতে একটি খুলুন।",
  "Waiting for verification": "যাচাইয়ের অপেক্ষায়",
  "{n} NGOs and volunteers to review": "{n}টি এনজিও ও স্বেচ্ছাসেবক যাচাই বাকি",
  "No one waiting": "কেউ অপেক্ষায় নেই",
  "All pending": "সব অপেক্ষমাণ",
  "Registered": "নিবন্ধিত",
  "All caught up": "সব কাজ শেষ",
  "New NGO and volunteer sign-ups appear here for review.": "নতুন এনজিও ও স্বেচ্ছাসেবকের নিবন্ধন যাচাইয়ের জন্য এখানে দেখা যাবে।",
  "Recent activity": "সাম্প্রতিক কার্যক্রম",
  "Latest donation status changes.": "দানের অবস্থার সর্বশেষ পরিবর্তন।",
  "Activity log": "কার্যক্রমের লগ",
  "System": "সিস্টেম",
  "No activity yet": "এখনো কোনো কার্যক্রম নেই",
  "other pending accounts.": "অন্যান্য অপেক্ষমাণ অ্যাকাউন্ট।",
  "Review": "দেখুন",
  "Waiting for a volunteer": "স্বেচ্ছাসেবকের অপেক্ষায়",
  "Allocated more than {n} minutes ago and nobody has accepted. Offer it to someone.": "{n} মিনিটেরও বেশি আগে বরাদ্দ হয়েছে কিন্তু কেউ নেননি। কাউকে প্রস্তাব দিন।",
  "To {ngo}": "{ngo}-এর জন্য",
  "an NGO": "একটি এনজিও",
  "allocated {time}": "বরাদ্দ {time}",
  "Open to all": "সবার জন্য খোলা",
  "Pickup overdue": "সংগ্রহে দেরি",
  "A volunteer accepted but hasn’t picked up {n}+ minutes after the pickup time. Call them or release the task.": "স্বেচ্ছাসেবক কাজটি নিয়েছেন কিন্তু সংগ্রহের সময়ের {n}+ মিনিট পরেও সংগ্রহ করেননি। তাকে ফোন করুন বা কাজটি ছেড়ে দিন।",
  "pickup was {time}": "সংগ্রহের সময় ছিল {time}",
  "Delivery not confirmed": "ডেলিভারি নিশ্চিত হয়নি",
  "Picked up but no update for {n}+ hours. Check with the volunteer or NGO and record the delivery.": "সংগ্রহ হয়েছে কিন্তু {n}+ ঘণ্টা কোনো আপডেট নেই। স্বেচ্ছাসেবক বা এনজিওর সঙ্গে কথা বলে ডেলিভারি রেকর্ড করুন।",
  "last update {time}": "সর্বশেষ আপডেট {time}",
  "Meals served not recorded": "পরিবেশিত বেলার খাবার রেকর্ড হয়নি",
  "Delivered {n}+ hours ago; the NGO hasn’t recorded how many people ate.": "{n}+ ঘণ্টা আগে পৌঁছেছে; এনজিও কতজন খেয়েছেন তা রেকর্ড করেনি।",
  "delivered {time}": "পৌঁছেছে {time}",
  "Food requests with no match": "মিল না পাওয়া খাবারের অনুরোধ",
  "Needed within {n} hours and no food has been matched. Contact the NGO or nearby donors.": "{n} ঘণ্টার মধ্যে দরকার কিন্তু কোনো খাবার মেলেনি। এনজিও বা কাছের দাতাদের সঙ্গে যোগাযোগ করুন।",
  "Needed {time}": "দরকার {time}",
  "Needs attention": "মনোযোগ দরকার",
  "{n} item stuck in the workflow, oldest first.": "কাজের ধারায় {n}টি বিষয় আটকে আছে, সবচেয়ে পুরোনোটি আগে।",
  "{n} items stuck in the workflow, oldest first.": "কাজের ধারায় {n}টি বিষয় আটকে আছে, সবচেয়ে পুরোনোটি আগে।",
  "Nothing is stuck right now.": "এখন কিছুই আটকে নেই।",
  "All requests": "সব অনুরোধ",
  "And {n} more.": "আরও {n}টি।",
  "See donations": "দানগুলো দেখুন",
  "All pickups and deliveries are moving.": "সব সংগ্রহ ও ডেলিভারি চলমান।",
  "{n} expired": "{n}টি মেয়াদোত্তীর্ণ",
  "in the last {n} hours": "গত {n} ঘণ্টায়",
  "Review expired food": "মেয়াদোত্তীর্ণ খাবার দেখুন",
  "Approve": "অনুমোদন করুন",
  "Verify": "যাচাই করুন",
  "Reactivate": "আবার সক্রিয় করুন",
  "Suspend": "স্থগিত করুন",
  "Reject (suspend)": "প্রত্যাখ্যান (স্থগিত)",
  "Deactivate": "নিষ্ক্রিয় করুন",
  "the user can’t log in until reactivated.": "আবার সক্রিয় না করা পর্যন্ত ব্যবহারকারী লগ ইন করতে পারবেন না।",
  "Assigned pickups go back to other volunteers.": "নির্ধারিত সংগ্রহের কাজগুলো অন্য স্বেচ্ছাসেবকদের কাছে ফিরে যাবে।",
  "Open food requests are cancelled and pending requests withdrawn.": "খোলা খাবারের অনুরোধগুলো বাতিল হবে এবং অপেক্ষমাণ অনুরোধগুলো প্রত্যাহার হবে।",
  "Donations nobody has matched yet are cancelled.": "যেসব দান এখনো কারও সঙ্গে মেলেনি সেগুলো বাতিল হবে।",
  "(optional, kept in the admin log)": "(ঐচ্ছিক, অ্যাডমিন লগে রাখা হবে)",
  "Confirm: {action}": "নিশ্চিত করুন: {action}",
  "User": "ব্যবহারকারী",
  "Donors, NGOs and volunteers. Verify, suspend or deactivate accounts.": "দাতা, এনজিও ও স্বেচ্ছাসেবক। অ্যাকাউন্ট যাচাই, স্থগিত বা নিষ্ক্রিয় করুন।",
  "Everyone": "সবাই",
  "Name, email, phone or organisation": "নাম, ইমেইল, ফোন বা প্রতিষ্ঠান",
  "Name": "নাম",
  "Role": "ভূমিকা",
  "Received": "পাওয়া",
  "Joined": "যোগদান",
  "No users found": "কোনো ব্যবহারকারী পাওয়া যায়নি",
  "Try a different search or clear the filters.": "অন্যভাবে খুঁজুন বা ফিল্টার মুছে দিন।",
  "Recent donations": "সাম্প্রতিক দান",
  "Donations received": "পাওয়া দান",
  "Delivery tasks": "ডেলিভারির কাজ",
  "Details": "বিবরণ",
  "Business": "ব্যবসা",
  "About": "সম্পর্কে",
  "Updated": "হালনাগাদ",
  "Nothing yet.": "এখনো কিছু নেই।",
  "Admin history": "অ্যাডমিন ইতিহাস",
  "Verification and account changes.": "যাচাই ও অ্যাকাউন্টের পরিবর্তন।",
  "No admin actions yet.": "এখনো কোনো অ্যাডমিন পদক্ষেপ নেই।",
  "Approved account": "অ্যাকাউন্ট অনুমোদিত",
  "Suspended account": "অ্যাকাউন্ট স্থগিত",
  "Deactivated account": "অ্যাকাউন্ট নিষ্ক্রিয়",
  "Reactivated account": "অ্যাকাউন্ট আবার সক্রিয়",
  "Edited details": "বিবরণ সম্পাদিত",
  "Released volunteer": "স্বেচ্ছাসেবককে সরানো হয়েছে",
  "Accepted match for NGO": "এনজিওর হয়ে মিল গ্রহণ",
  "Rejected match": "মিল প্রত্যাখ্যাত",
  "Cancelled allocated match": "বরাদ্দ মিল বাতিল",
  "Paused for a safety check": "নিরাপত্তা যাচাইয়ের জন্য স্থগিত",
  "Cleared the safety check": "নিরাপত্তা যাচাই সম্পন্ন",
  "Withdrew food as unsafe": "অনিরাপদ হিসেবে খাবার প্রত্যাহার",
  "Exported data": "তথ্য রপ্তানি",
  "Offered the pickup to a volunteer": "স্বেচ্ছাসেবককে সংগ্রহের কাজ প্রস্তাব",
  "Confirmed delivery on a volunteer’s behalf": "স্বেচ্ছাসেবকের হয়ে ডেলিভারি নিশ্চিত",
  "Recorded meals served for the NGO": "এনজিওর হয়ে পরিবেশিত বেলার খাবার রেকর্ড",
  "Changed password": "পাসওয়ার্ড বদলানো হয়েছে",
  "Sign-in paused after failed attempts": "ব্যর্থ চেষ্টার পর সাইন ইন সাময়িক বন্ধ",
  "Every donation from posting to distribution. Open one to update, cancel or trace it.": "পোস্ট থেকে বিতরণ পর্যন্ত প্রতিটি দান। হালনাগাদ, বাতিল বা অনুসরণ করতে একটি খুলুন।",
  "Food, donor or NGO": "খাবার, দাতা বা এনজিও",
  "NGO / volunteer": "এনজিও / স্বেচ্ছাসেবক",
  "Volunteer: {name}": "স্বেচ্ছাসেবক: {name}",
  "No donations found": "কোনো দান পাওয়া যায়নি",
  "Important actions on the platform: verifications, suspensions, corrections, cancellations, exports and sign-in alerts.": "প্ল্যাটফর্মের গুরুত্বপূর্ণ পদক্ষেপ: যাচাই, স্থগিত, সংশোধন, বাতিল, রপ্তানি ও সাইন-ইন সতর্কবার্তা।",
  "Everything": "সবকিছু",
  "Action": "পদক্ষেপ",
  "Any action": "যেকোনো পদক্ষেপ",
  "Who, what or note": "কে, কী বা নোট",
  "When": "কখন",
  "By": "করেছেন",
  "Security": "নিরাপত্তা",
  "No activity found": "কোনো কার্যক্রম পাওয়া যায়নি",
  "Admin actions, exports and sign-in alerts appear here.": "অ্যাডমিন পদক্ষেপ, রপ্তানি ও সাইন-ইন সতর্কবার্তা এখানে দেখা যাবে।",
  "Report data": "রিপোর্টের তথ্য",
  "Removed record": "মুছে ফেলা রেকর্ড",
  "NGO food requests, the donations requested or matched for them, and what was allocated where.": "এনজিওর খাবারের অনুরোধ, সেগুলোর জন্য অনুরোধ করা বা মেলানো দান, এবং কী কোথায় বরাদ্দ হয়েছে।",
  "Donation requests & matches": "দানের অনুরোধ ও মিল",
  "Allocations": "বরাদ্দ",
  "Allocated to": "যাকে বরাদ্দ",
  "System match": "সিস্টেমের মিল",
  "Direct request": "সরাসরি অনুরোধ",
  "system match": "সিস্টেমের মিল",
  "direct": "সরাসরি",
  "Nothing allocated yet": "এখনো কিছু বরাদ্দ হয়নি",
  "Accepted matches and requests appear here.": "গৃহীত মিল ও অনুরোধ এখানে দেখা যাবে।",
  "NGO or food": "এনজিও বা খাবার",
  "Request": "অনুরোধ",
  "Progress (meals)": "অগ্রগতি (বেলার খাবার)",
  "Cancel": "বাতিল করুন",
  "No food requests found": "কোনো খাবারের অনুরোধ পাওয়া যায়নি",
  "NGOs’ food requests appear here.": "এনজিওগুলোর খাবারের অনুরোধ এখানে দেখা যাবে।",
  "Request status": "অনুরোধের অবস্থা",
  "Donation status": "দানের অবস্থা",
  "Withdraw": "প্রত্যাহার করুন",
  "No requests found": "কোনো অনুরোধ পাওয়া যায়নি",
  "Food donated, distributed and lost, from the donation records. Filter by date, location, donor type and status.": "দানের রেকর্ড থেকে দান, বিতরণ ও নষ্ট হওয়া খাবার। তারিখ, অবস্থান, দাতার ধরন ও অবস্থা অনুযায়ী ফিল্টার করুন।",
  "Area, e.g. Mirpur": "এলাকা, যেমন: মিরপুর",
  "All donor types": "সব ধরনের দাতা",
  "Export CSV": "CSV রপ্তানি",
  "Report summary": "রিপোর্টের সারসংক্ষেপ",
  "Exports use these filters (users: location and date joined) and leave out contact details, home addresses and exact locations. Each export is logged.": "রপ্তানিতে এই ফিল্টারগুলো ব্যবহৃত হয় (ব্যবহারকারী: অবস্থান ও যোগদানের তারিখ), এবং যোগাযোগের তথ্য, বাসার ঠিকানা ও সঠিক অবস্থান বাদ দেওয়া হয়। প্রতিটি রপ্তানি লগে রাখা হয়।",
  "When the food was posted.": "খাবার যখন পোস্ট করা হয়েছে।",
  "By area": "এলাকা অনুযায়ী",
  "The donor’s area (top 25).": "দাতার এলাকা (শীর্ষ ২৫)।",
  "By donor type": "দাতার ধরন অনুযায়ী",
  "unavailable": "ব্যস্ত",
  "{n} active": "{n}টি চলমান",
  "No verified volunteers yet. Approve one under Users first.": "এখনো কোনো যাচাই করা স্বেচ্ছাসেবক নেই। আগে “ব্যবহারকারী” অংশ থেকে একজনকে অনুমোদন করুন।",
  "They get the task first and can still accept or decline.": "কাজটি আগে তার কাছে যাবে, তিনি তবুও গ্রহণ বা প্রত্যাখ্যান করতে পারবেন।",
  "Offer the pickup": "সংগ্রহের কাজ প্রস্তাব করুন",
  "How do you know it arrived?": "কীভাবে জানলেন যে পৌঁছেছে?",
  "e.g. NGO called to confirm": "যেমন: এনজিও ফোন করে নিশ্চিত করেছে",
  "Shown in the donation’s timeline.": "দানের সময়রেখায় দেখানো হবে।",
  "Mark as delivered": "পৌঁছেছে হিসেবে চিহ্নিত করুন",
  "Contact name": "যোগাযোগের নাম",
  "posted {time}": "পোস্ট {time}",
  "Remainder of a partly allocated donation": "আংশিক বরাদ্দ করা দানের বাকি অংশ",
  "see the original": "মূল দান দেখুন",
  "Not matched yet": "এখনো মেলেনি",
  "Not assigned": "নির্ধারিত হয়নি",
  "Status timeline": "অবস্থার সময়রেখা",
  "Activity history": "কার্যক্রমের ইতিহাস",
  "Every status change, who made it and when.": "অবস্থার প্রতিটি পরিবর্তন, কে করেছেন এবং কখন।",
  "NGO requests & matches": "এনজিওর অনুরোধ ও মিল",
  "Direct requests and system matches. Accept, reject or cancel on an NGO’s behalf.": "সরাসরি অনুরোধ ও সিস্টেমের মিল। এনজিওর হয়ে গ্রহণ, প্রত্যাখ্যান বা বাতিল করুন।",
  "For": "জন্য",
  "Matched to a food request": "খাবারের অনুরোধের সঙ্গে মিলেছে",
  "Accept for NGO": "এনজিওর হয়ে গ্রহণ করুন",
  "No NGO has requested this donation.": "কোনো এনজিও এই দানের অনুরোধ করেনি।",
  "Which NGO this food (and any part split from it) was proposed and allocated to.": "এই খাবার (এবং এর থেকে আলাদা হওয়া অংশ) কোন এনজিওকে প্রস্তাব ও বরাদ্দ করা হয়েছে।",
  "Volunteer assignment": "স্বেচ্ছাসেবক নির্ধারণ",
  "Who the pickup was offered to, nearest first, and their answers.": "সংগ্রহের কাজটি কাকে কাকে প্রস্তাব করা হয়েছে (সবচেয়ে কাছের আগে) এবং তাদের উত্তর।",
  "Distance": "দূরত্ব",
  "Offered": "প্রস্তাবিত",
  "Answer": "উত্তর",
  "Pause food with incomplete or doubtful safety details, or withdraw it.": "নিরাপত্তার তথ্য অসম্পূর্ণ বা সন্দেহজনক হলে খাবার স্থগিত বা প্রত্যাহার করুন।",
  "Prepared": "রান্না/প্রস্তুত",
  "What needs checking?": "কী যাচাই করা দরকার?",
  "(sent to the donor)": "(দাতাকে পাঠানো হবে)",
  "e.g. No prepared time for cooked rice": "যেমন: রান্না করা ভাতের প্রস্তুতের সময় দেওয়া নেই",
  "Pause for safety check": "নিরাপত্তা যাচাইয়ের জন্য স্থগিত করুন",
  "Checked: make it available again": "যাচাই শেষ: আবার পাওয়া যাবে এমন করুন",
  "Why it’s unsafe": "কেন অনিরাপদ",
  "Why it’s unsafe (sent to everyone involved)": "কেন অনিরাপদ (সংশ্লিষ্ট সবাইকে পাঠানো হবে)",
  "Withdraw as unsafe": "অনিরাপদ হিসেবে প্রত্যাহার করুন",
  "Control": "নিয়ন্ত্রণ",
  "Step in when something is stuck. Every action is written to the activity log.": "কিছু আটকে গেলে হস্তক্ষেপ করুন। প্রতিটি পদক্ষেপ কার্যক্রমের লগে লেখা হয়।",
  "Offer to a volunteer": "স্বেচ্ছাসেবককে প্রস্তাব করুন",
  "No volunteer has taken this pickup yet. Pick someone you’ve spoken to.": "এখনো কোনো স্বেচ্ছাসেবক এই সংগ্রহের কাজ নেননি। যার সঙ্গে কথা বলেছেন তাকে বেছে নিন।",
  "Record the delivery": "ডেলিভারি রেকর্ড করুন",
  "Use this when the food arrived but nobody confirmed it in the app.": "খাবার পৌঁছেছে কিন্তু অ্যাপে কেউ নিশ্চিত করেননি, এমন হলে এটি ব্যবহার করুন।",
  "Record meals served": "পরিবেশিত বেলার খাবার রেকর্ড করুন",
  "For when {ngo} has told you how many people ate.": "{ngo} কতজন খেয়েছেন জানালে এটি ব্যবহার করুন।",
  "Take the task away from {name} and offer it to others.": "{name}-এর কাছ থেকে কাজটি সরিয়ে অন্যদের প্রস্তাব করুন।",
  "the volunteer": "স্বেচ্ছাসেবক",
  "Release volunteer": "স্বেচ্ছাসেবককে সরান",
  "Cancel reason": "বাতিলের কারণ",
  "(sent to donor, NGO and volunteer)": "(দাতা, এনজিও ও স্বেচ্ছাসেবককে পাঠানো হবে)",
  "Update details": "বিবরণ হালনাগাদ করুন",
  "Corrections only. Status changes follow the workflow.": "শুধু সংশোধন। অবস্থার পরিবর্তন নিয়ম অনুযায়ী হয়।",
  "Ready": "প্রস্তুত",
};
