export const COMMON: Record<string, string> = {
  "Skip to content": "মূল অংশে যান",
  "FoodWasteZero initiative": "ফুডওয়েস্টজিরো উদ্যোগ",
  "Need help?": "সাহায্য দরকার?",
  "Overview": "সারসংক্ষেপ",
  "My donations": "আমার দান",
  "Map": "মানচিত্র",
  "Alerts": "সতর্কবার্তা",
  "Food requests": "খাবারের অনুরোধ",
  "Report": "রিপোর্ট",
  "My tasks": "আমার কাজ",
  "Users": "ব্যবহারকারী",
  "Donations": "দান",
  "Requests": "অনুরোধ",
  "Activity": "কার্যক্রম",
  "Reports": "রিপোর্ট",
  "Donate food": "খাবার দান করুন",
  "Donate": "দান",
  "Find food": "খাবার খুঁজুন",
  "Tasks": "কাজ",
  "Profile": "প্রোফাইল",
  "Notifications, {n} unread": "নোটিফিকেশন, {n}টি অপঠিত",
  "Notifications": "নোটিফিকেশন",
  "Language": "ভাষা",
  "Account menu": "অ্যাকাউন্ট মেনু",
  "{role} account": "{role} অ্যাকাউন্ট",
  "Profile & settings": "প্রোফাইল ও সেটিংস",
  "Ask FoodBridge (assistant)": "ফুডব্রিজকে জিজ্ঞাসা করুন (সহকারী)",
  "Log out": "লগ আউট",
  "Quick navigation": "দ্রুত নেভিগেশন",
  "Home": "হোম",
  "(optional)": "(ঐচ্ছিক)",
  "Close": "বন্ধ করুন",
  "Loading…": "লোড হচ্ছে…",
  "Something went wrong": "কিছু একটা ভুল হয়েছে",
  "Please try again. If the problem continues, contact support.": "আবার চেষ্টা করুন। সমস্যা থেকে গেলে সহায়তা দলের সঙ্গে যোগাযোগ করুন।",
  "Donor": "দাতা",
  "NGO": "এনজিও",
  "Volunteer": "স্বেচ্ছাসেবক",
  "Admin": "অ্যাডমিন",
  "Donors": "দাতারা",
  "NGOs": "এনজিও",
  "Volunteers": "স্বেচ্ছাসেবকেরা",
  "Cooked meals": "রান্না করা খাবার",
  "Bakery": "বেকারি",
  "Packaged / dry food": "প্যাকেটজাত / শুকনো খাবার",
  "Raw ingredients": "কাঁচা উপকরণ",
  "Fruits & vegetables": "ফল ও সবজি",
  "Dairy": "দুগ্ধজাত",
  "Other": "অন্যান্য",
  "Plates / servings": "প্লেট / পরিবেশন",
  "Kilograms (kg)": "কিলোগ্রাম (কেজি)",
  "Packets": "প্যাকেট",
  "Boxes": "বাক্স",
  "Litres": "লিটার",
  "Pieces": "পিস",
  "plates": "প্লেট",
  "kg": "কেজি",
  "packets": "প্যাকেট",
  "boxes": "বাক্স",
  "L": "লিটার",
  "pcs": "পিস",
  "Fresh — just prepared / unopened": "টাটকা — সদ্য রান্না / না-খোলা",
  "Good — safe, stored properly": "ভালো — নিরাপদ, ঠিকমতো সংরক্ষিত",
  "Consume soon — best within a few hours": "দ্রুত খেতে হবে — কয়েক ঘণ্টার মধ্যে খাওয়াই ভালো",
  "Restaurant": "রেস্তোরাঁ",
  "Hotel": "হোটেল",
  "Shop / Supermarket": "দোকান / সুপারমার্কেট",
  "Individual / Household": "ব্যক্তি / পরিবার",
  "Other (event, office, caterer…)": "অন্যান্য (অনুষ্ঠান, অফিস, ক্যাটারার…)",
  "Pending": "অপেক্ষমাণ",
  "Matched": "মিলেছে",
  "Volunteer assigned": "স্বেচ্ছাসেবক নির্ধারিত",
  "Picked up": "সংগ্রহ হয়েছে",
  "In transit": "পথে আছে",
  "Delivered": "পৌঁছেছে",
  "Completed": "সম্পন্ন",
  "Cancelled": "বাতিল",
  "Expired": "মেয়াদোত্তীর্ণ",
  "Open for NGO requests. Accept one to match it.": "এনজিওর অনুরোধের জন্য খোলা। মেলাতে একটি অনুরোধ গ্রহণ করুন।",
  "Matched with an NGO. A volunteer will be assigned next.": "একটি এনজিওর সঙ্গে মিলেছে। এরপর একজন স্বেচ্ছাসেবক নির্ধারণ করা হবে।",
  "A volunteer is coming to pick it up.": "একজন স্বেচ্ছাসেবক খাবার নিতে আসছেন।",
  "Food collected from the donor.": "দাতার কাছ থেকে খাবার সংগ্রহ করা হয়েছে।",
  "The volunteer is on the way to the NGO.": "স্বেচ্ছাসেবক এনজিওর দিকে যাচ্ছেন।",
  "Delivered to the NGO.": "এনজিওর কাছে পৌঁছে দেওয়া হয়েছে।",
  "Distributed to people in need. Thank you!": "প্রয়োজনে থাকা মানুষের মাঝে বিতরণ করা হয়েছে। ধন্যবাদ!",
  "This donation was cancelled.": "এই দানটি বাতিল করা হয়েছে।",
  "Not picked up before the best-before time.": "খাওয়ার শেষ সময়ের আগে সংগ্রহ করা হয়নি।",
  "Shelter / homeless support": "আশ্রয়কেন্দ্র / গৃহহীন সহায়তা",
  "Orphanage / children’s home": "এতিমখানা / শিশু নিবাস",
  "Community kitchen": "কমিউনিটি কিচেন",
  "Elderly home": "বৃদ্ধাশ্রম",
  "School / madrasa": "স্কুল / মাদ্রাসা",
  "Other charity": "অন্যান্য দাতব্য সংস্থা",
  "Accepted": "গৃহীত",
  "Waiting for the donor to accept, or for suitable food to be found.": "দাতার সম্মতি বা উপযুক্ত খাবার পাওয়ার অপেক্ষায়।",
  "We found suitable food. Review it and confirm to accept.": "উপযুক্ত খাবার পাওয়া গেছে। দেখে নিয়ে গ্রহণ নিশ্চিত করুন।",
  "The food is yours. A volunteer picks it up and brings it to you.": "খাবারটি আপনার। একজন স্বেচ্ছাসেবক তা সংগ্রহ করে আপনার কাছে নিয়ে আসবেন।",
  "Food delivered. Mark it distributed once served.": "খাবার পৌঁছেছে। পরিবেশনের পর বিতরণ সম্পন্ন হিসেবে চিহ্নিত করুন।",
  "This request is no longer active.": "এই অনুরোধটি আর সক্রিয় নেই।",
  "This food went to another NGO, or it was cancelled.": "খাবারটি অন্য এনজিওর কাছে গেছে, অথবা বাতিল হয়েছে।",
  "You passed on this match.": "আপনি এই মিলটি বাদ দিয়েছেন।",
  "This request was withdrawn.": "এই অনুরোধটি প্রত্যাহার করা হয়েছে।",
  "The food expired before it could be matched.": "মেলানোর আগেই খাবারের মেয়াদ শেষ হয়ে গেছে।",
  "Any time": "যেকোনো সময়",
  "Expires within 2 hours": "২ ঘণ্টার মধ্যে মেয়াদ শেষ",
  "Expires within 6 hours": "৬ ঘণ্টার মধ্যে মেয়াদ শেষ",
  "Expires within 24 hours": "২৪ ঘণ্টার মধ্যে মেয়াদ শেষ",
  "This request was cancelled.": "এই অনুরোধটি বাতিল করা হয়েছে।",
  "You closed this request.": "আপনি এই অনুরোধটি বন্ধ করেছেন।",
  "The required time passed before food was found.": "খাবার পাওয়ার আগেই প্রয়োজনের সময় পেরিয়ে গেছে।",
  "Safe": "নিরাপদ",
  "Expiring soon": "শীঘ্রই মেয়াদ শেষ",
  "Safety check": "নিরাপত্তা যাচাই",
  "Withdrawn": "প্রত্যাহার করা হয়েছে",
  "Within its safe time window.": "নিরাপদ সময়সীমার মধ্যে আছে।",
  "Less than an hour of safe time left.": "নিরাপদ সময়ের এক ঘণ্টারও কম বাকি।",
  "Past its best-before time. It can’t be matched or delivered.": "খাওয়ার শেষ সময় পেরিয়ে গেছে। এটি আর মেলানো বা পৌঁছানো যাবে না।",
  "Paused by FoodBridge until the food-safety details are checked.": "খাদ্য-নিরাপত্তার তথ্য যাচাই না হওয়া পর্যন্ত ফুডব্রিজ এটি স্থগিত রেখেছে।",
  "Withdrawn by FoodBridge for food-safety reasons.": "খাদ্য-নিরাপত্তার কারণে ফুডব্রিজ এটি প্রত্যাহার করেছে।",
  "For this food type, best-before can be at most {limit} after it was prepared.": "এই ধরনের খাবারের ক্ষেত্রে খাওয়ার শেষ সময় রান্নার পর সর্বোচ্চ {limit} হতে পারে।",
  "“Consume soon” food can be listed for at most {n} hours from now.": "“দ্রুত খেতে হবে” খাবার এখন থেকে সর্বোচ্চ {n} ঘণ্টার জন্য তালিকাভুক্ত করা যায়।",
  "{n} hours": "{n} ঘণ্টা",
  "{n} days": "{n} দিন",
  "Assigned to you": "আপনাকে দেওয়া হয়েছে",
  "Open": "খোলা",
  "Closed": "বন্ধ",
  "Assigned": "নির্ধারিত",
  "You’re the nearest available volunteer. Accept or decline this pickup.": "আপনিই সবচেয়ে কাছের ফাঁকা স্বেচ্ছাসেবক। এই সংগ্রহের কাজটি গ্রহণ বা প্রত্যাখ্যান করুন।",
  "No one nearby has taken this pickup yet. Accept it if you can help.": "কাছাকাছি কেউ এখনো এই সংগ্রহের কাজটি নেননি। সাহায্য করতে পারলে গ্রহণ করুন।",
  "Go to the donor and confirm pickup once you have the food.": "দাতার কাছে যান এবং খাবার হাতে পেলে সংগ্রহ নিশ্চিত করুন।",
  "Start the delivery when you set off for the NGO.": "এনজিওর উদ্দেশে রওনা হলে ডেলিভারি শুরু করুন।",
  "Take the food to the NGO and confirm delivery.": "খাবার এনজিওর কাছে নিয়ে যান এবং পৌঁছানো নিশ্চিত করুন।",
  "Delivered. Thank you for volunteering!": "পৌঁছে দেওয়া হয়েছে। স্বেচ্ছাসেবার জন্য ধন্যবাদ!",
  "The NGO served this food. Thank you!": "এনজিও এই খাবার পরিবেশন করেছে। ধন্যবাদ!",
  "This task was cancelled, the food expired, or it went to another volunteer.": "এই কাজটি বাতিল হয়েছে, খাবারের মেয়াদ শেষ হয়েছে, অথবা অন্য স্বেচ্ছাসেবকের কাছে গেছে।",
  "Waiting for reply": "উত্তরের অপেক্ষায়",
  "Declined": "প্রত্যাখ্যাত",
  "No reply in time": "সময়মতো উত্তর মেলেনি",
  "Handed back": "ফেরত দেওয়া হয়েছে",
  "Donation created": "দান তৈরি হয়েছে",
  "Match found": "মিল পাওয়া গেছে",
  "Request accepted": "অনুরোধ গৃহীত",
  "Pickup confirmed": "সংগ্রহ নিশ্চিত",
  "Delivery completed": "ডেলিভারি সম্পন্ন",
  "Expiry & safety": "মেয়াদ ও নিরাপত্তা",
  "Other updates": "অন্যান্য আপডেট",
  "Email": "ইমেইল",
  "SMS": "এসএমএস",
  "WhatsApp": "হোয়াটসঅ্যাপ",
  "Messenger": "মেসেঞ্জার",
  "Active": "সক্রিয়",
  "Suspended": "স্থগিত",
  "Deactivated": "নিষ্ক্রিয়",
  "Waiting for donor": "দাতার অপেক্ষায়",
  "Matched, awaiting NGO": "মিলেছে, এনজিওর অপেক্ষায়",
  "Skipped by NGO": "এনজিও বাদ দিয়েছে",
  "Accounts": "অ্যাকাউন্ট",
  "Requests & matches": "অনুরোধ ও মিল",
  "Created": "তৈরি হয়েছে",
  "(current step)": "(বর্তমান ধাপ)",
  "{n} request": "{n}টি অনুরোধ",
  "{n} requests": "{n}টি অনুরোধ",
  "~{n} meals": "~{n} বেলার খাবার",
  "{n} meals": "{n} বেলার খাবার",
  "View all": "সব দেখুন",
  "All": "সব",
  "Period": "সময়কাল",
  "Nothing in this period yet": "এই সময়ে এখনো কিছু নেই",
  "7 days": "৭ দিন",
  "30 days": "৩০ দিন",
  "90 days": "৯০ দিন",
  "12 months": "১২ মাস",
  "Jan": "জানু",
  "Feb": "ফেব্রু",
  "Mar": "মার্চ",
  "Apr": "এপ্রি",
  "May": "মে",
  "Jun": "জুন",
  "Jul": "জুলা",
  "Aug": "আগ",
  "Sep": "সেপ্টে",
  "Oct": "অক্টো",
  "Nov": "নভে",
  "Dec": "ডিসে",
  "Good morning": "শুভ সকাল",
  "Good afternoon": "শুভ অপরাহ্ন",
  "Good evening": "শুভ সন্ধ্যা",
  "{greeting}, {name}": "{greeting}, {name}",
  "{type} dashboard": "{type} ড্যাশবোর্ড",
  "Back to dashboard": "ড্যাশবোর্ডে ফিরুন",
  "Still needed: {list}.": "এখনো দরকার: {list}।",
  "Verified": "যাচাই করা",
  "{d} away": "{d} দূরে",
  "{n} km": "{n} কিমি",
  "{n} m": "{n} মিটার",
  "{n} people": "{n} জন",
  "Decline": "প্রত্যাখ্যান",
  "Accept": "গ্রহণ করুন",
  "Category": "বিভাগ",
  "Quantity": "পরিমাণ",
  "Condition": "অবস্থা",
  "Prepared at": "রান্না/প্রস্তুতের সময়",
  "Best before": "খাওয়ার শেষ সময়",
  "Special instructions": "বিশেষ নির্দেশনা",
  "Address": "ঠিকানা",
  "Contact": "যোগাযোগ",
  "Delivery": "ডেলিভারি",
  "Tracking": "অবস্থা অনুসরণ",
  "Food details": "খাবারের বিবরণ",
  "Pickup": "সংগ্রহ",
  "Reason": "কারণ",
  "Cancelling…": "বাতিল করা হচ্ছে…",
  "Accepting…": "গ্রহণ করা হচ্ছে…",
  "Updating…": "হালনাগাদ হচ্ছে…",
  "Note: {note}": "নোট: {note}",
  "Cancelled: {reason}": "বাতিল: {reason}",
  "Posted {time}": "পোস্ট {time}",
  "by {time}": "{time}-এর মধ্যে",
  "Photo of {food}": "{food}-এর ছবি",
  "Ready from": "প্রস্তুত থাকবে",
  "Delivering to": "পৌঁছানো হবে",
  "(done)": "(সম্পন্ন)",
  "(not yet)": "(এখনো নয়)",
  "Step {n} of {total}: {label}": "ধাপ {n}/{total}: {label}",
  "Posted": "পোস্ট হয়েছে",
  "On the way": "পথে",
  "Who’s helping": "যারা সাহায্য করছেন",
  "Demo mode": "ডেমো মোড",
  "Move to “{label}”": "“{label}” ধাপে নিন",
  "No map pin: distances use your area.": "মানচিত্রে পিন নেই: দূরত্ব আপনার এলাকা ধরে হিসাব করা হয়।",
  "Delivery progress": "ডেলিভারির অগ্রগতি",
  "The volunteer": "স্বেচ্ছাসেবক",
  "Offered to the nearest available volunteer. Waiting for them to accept.": "সবচেয়ে কাছের ফাঁকা স্বেচ্ছাসেবককে প্রস্তাব দেওয়া হয়েছে। তার সম্মতির অপেক্ষায়।",
  "Looking for a volunteer. Every available volunteer can accept this pickup.": "স্বেচ্ছাসেবক খোঁজা হচ্ছে। যেকোনো ফাঁকা স্বেচ্ছাসেবক এই সংগ্রহের কাজটি নিতে পারেন।",
  "{who} accepted and is heading to the pickup.": "{who} কাজটি নিয়েছেন এবং সংগ্রহের জায়গায় যাচ্ছেন।",
  "{who} collected the food.": "{who} খাবার সংগ্রহ করেছেন।",
  "{who} is on the way to the NGO.": "{who} এনজিওর দিকে যাচ্ছেন।",
  "Delivered and served. Thank you!": "পৌঁছে পরিবেশন করা হয়েছে। ধন্যবাদ!",
  "This delivery is closed.": "এই ডেলিভারিটি বন্ধ।",
  "Food": "খাবার",
  "Required time": "নির্ধারিত সময়",
  "Pick up from {time}": "সংগ্রহ: {time} থেকে",
  "Deliver by {time} ({relative})": "পৌঁছাতে হবে {time}-এর মধ্যে ({relative})",
  "Pickup (donor)": "সংগ্রহ (দাতা)",
  "Delivery (NGO)": "ডেলিভারি (এনজিও)",
  "{d} from the pickup": "সংগ্রহের জায়গা থেকে {d}",
  "{name} · pickup": "{name} · সংগ্রহ",
  "{name} · delivery": "{name} · ডেলিভারি",
  "Carrying {food}": "{food} নিয়ে যাচ্ছেন",
  "awaiting verification": "যাচাইয়ের অপেক্ষায়",
  "available": "ফাঁকা আছেন",
  "offline": "অফলাইন",
  "Available · {donor}": "পাওয়া যাচ্ছে · {donor}",
  "Household donor": "পারিবারিক দাতা",
  "approximate area": "আনুমানিক এলাকা",
  "your task": "আপনার কাজ",
  "assigned to you": "আপনাকে দেওয়া হয়েছে",
  "open": "খোলা",
  "Waiting for an NGO": "এনজিওর অপেক্ষায়",
  "litres": "লিটার",
  "pieces": "পিস",
  "Food pickups": "খাবার সংগ্রহের জায়গা",
  "NGOs & delivery points": "এনজিও ও ডেলিভারির জায়গা",
  "You": "আপনি",
  "Your saved location": "আপনার সংরক্ষিত অবস্থান",
  "Show on map": "মানচিত্রে দেখান",
  "Nothing to show on the map yet.": "মানচিত্রে দেখানোর মতো এখনো কিছু নেই।",
  "Tap a pin for details. Dashed lines join a pickup to its delivery point. Faded pins with a circle are approximate (about 1 km) to protect private homes.": "বিস্তারিত দেখতে একটি পিনে চাপ দিন। ভাঙা রেখা সংগ্রহের জায়গাকে ডেলিভারির জায়গার সঙ্গে যুক্ত করে। ব্যক্তিগত বাড়ির গোপনীয়তা রক্ষায় বৃত্তসহ হালকা পিনগুলো আনুমানিক (প্রায় ১ কিমি)।",
  "Set your location to see distances.": "দূরত্ব দেখতে আপনার অবস্থান সেট করুন।",
  "Nearest to you": "আপনার সবচেয়ে কাছে",
  "This browser can’t share location. Pick the spot on the map instead.": "এই ব্রাউজার অবস্থান শেয়ার করতে পারে না। এর বদলে মানচিত্রে জায়গাটি বেছে নিন।",
  "Finding you…": "আপনার অবস্থান খোঁজা হচ্ছে…",
  "Located within about {n} m. Drag the pin to fine-tune.": "প্রায় {n} মিটারের মধ্যে অবস্থান পাওয়া গেছে। ঠিক জায়গায় নিতে পিনটি টেনে সরান।",
  "Location permission was denied. You can still tap the spot on the map.": "অবস্থানের অনুমতি দেওয়া হয়নি। আপনি তবুও মানচিত্রে জায়গাটিতে চাপ দিতে পারেন।",
  "Couldn’t get your location. Tap the spot on the map instead.": "আপনার অবস্থান পাওয়া যায়নি। এর বদলে মানচিত্রে জায়গাটিতে চাপ দিন।",
  "Use my current location": "আমার বর্তমান অবস্থান ব্যবহার করুন",
  "Hide map": "মানচিত্র লুকান",
  "Adjust on map": "মানচিত্রে ঠিক করুন",
  "Pick on map": "মানচিত্রে বেছে নিন",
  "Remove pin": "পিন সরান",
  "Pinned at {lat}, {lng}": "পিন: {lat}, {lng}",
  "A pin lets us show distances and find the nearest matches.": "পিন দিলে আমরা দূরত্ব দেখাতে ও সবচেয়ে কাছের মিল খুঁজে পেতে পারি।",
  "Chosen location": "বেছে নেওয়া অবস্থান",
  "Tap the map to place the pin": "পিন বসাতে মানচিত্রে চাপ দিন",
  "Tap the map or drag the pin to the exact spot.": "মানচিত্রে চাপ দিন বা পিনটি সঠিক জায়গায় টেনে নিন।",
  "This browser can’t share location. Set a pin on your profile instead.": "এই ব্রাউজার অবস্থান শেয়ার করতে পারে না। এর বদলে প্রোফাইলে একটি পিন দিন।",
  "Location updated. Nearby pickups come to you first.": "অবস্থান হালনাগাদ হয়েছে। কাছের সংগ্রহের কাজ আগে আপনার কাছে আসবে।",
  "Location permission was denied.": "অবস্থানের অনুমতি দেওয়া হয়নি।",
  "Couldn’t get your location. Try again.": "আপনার অবস্থান পাওয়া যায়নি। আবার চেষ্টা করুন।",
  "Saving…": "সংরক্ষণ হচ্ছে…",
  "Update my location": "আমার অবস্থান হালনাগাদ করুন",
  "Location from {time}": "অবস্থান: {time}",
  "Using your profile pin": "আপনার প্রোফাইলের পিন ব্যবহার করা হচ্ছে",
  "No location yet: tasks aren’t sorted by distance": "এখনো অবস্থান নেই: কাজগুলো দূরত্ব অনুযায়ী সাজানো নয়",
  "Loading map…": "মানচিত্র লোড হচ্ছে…",
  "Open details": "বিস্তারিত দেখুন",
  "Your food waiting for pickup, NGOs near you, and deliveries on the way.": "সংগ্রহের অপেক্ষায় থাকা আপনার খাবার, কাছের এনজিও এবং পথে থাকা ডেলিভারি।",
  "Donors, available food and volunteers around you, and deliveries coming to you.": "আপনার আশপাশের দাতা, পাওয়া যাচ্ছে এমন খাবার ও স্বেচ্ছাসেবক, এবং আপনার দিকে আসা ডেলিভারি।",
  "Donor pickup points for your tasks and open pickups, and where each one is delivered.": "আপনার কাজ ও খোলা সংগ্রহের জন্য দাতার ঠিকানা, এবং প্রতিটি কোথায় পৌঁছাতে হবে।",
  "Every NGO, volunteer and donor with a location, available food and active deliveries.": "অবস্থানসহ সব এনজিও, স্বেচ্ছাসেবক ও দাতা, পাওয়া যাচ্ছে এমন খাবার এবং চলমান ডেলিভারি।",
  "Pickup locations appear once your account is verified.": "অ্যাকাউন্ট যাচাই হলে সংগ্রহের জায়গাগুলো দেখা যাবে।",
  "This browser can’t share location.": "এই ব্রাউজার অবস্থান শেয়ার করতে পারে না।",
  "Location permission was denied. Allow it in your browser settings to share.": "অবস্থানের অনুমতি দেওয়া হয়নি। শেয়ার করতে ব্রাউজারের সেটিংসে অনুমতি দিন।",
  "Couldn’t get your location. Check GPS / location services and try again.": "আপনার অবস্থান পাওয়া যায়নি। জিপিএস / লোকেশন সার্ভিস দেখে আবার চেষ্টা করুন।",
  "Pickup: {name}": "সংগ্রহ: {name}",
  "Delivery: {name}": "ডেলিভারি: {name}",
  "{name} ({role}, live)": "{name} ({role}, সরাসরি)",
  "You (live)": "আপনি (সরাসরি)",
  "{name} (last known position)": "{name} (সর্বশেষ জানা অবস্থান)",
  "No map pins yet. Addresses are shown below; pins appear once donors and NGOs set their location.": "মানচিত্রে এখনো কোনো পিন নেই। ঠিকানা নিচে দেওয়া আছে; দাতা ও এনজিও অবস্থান দিলে পিন দেখা যাবে।",
  "Map legend": "মানচিত্রের চিহ্ন",
  "Volunteer → pickup": "স্বেচ্ছাসেবক → সংগ্রহ",
  "Volunteer → NGO": "স্বেচ্ছাসেবক → এনজিও",
  "Donor → NGO": "দাতা → এনজিও",
  "Route: you → donor → NGO": "পথ: আপনি → দাতা → এনজিও",
  "Navigate to NGO": "এনজিওর পথ দেখুন",
  "Open pickup in Maps": "সংগ্রহের জায়গা ম্যাপে খুলুন",
  "Open delivery in Maps": "ডেলিভারির জায়গা ম্যাপে খুলুন",
  "Live location": "সরাসরি অবস্থান",
  "Share yours so the donor and NGO can see you coming.": "আপনার অবস্থান শেয়ার করুন, যাতে দাতা ও এনজিও আপনার আসা দেখতে পান।",
  "Nobody is sharing right now. You’ll see the volunteer here if they share.": "এখন কেউ শেয়ার করছেন না। স্বেচ্ছাসেবক শেয়ার করলে এখানে দেখতে পাবেন।",
  "Starting…": "শুরু হচ্ছে…",
  "Stop sharing": "শেয়ার বন্ধ করুন",
  "Share my live location": "আমার সরাসরি অবস্থান শেয়ার করুন",
  "You’re sharing your live location with this delivery.": "আপনি এই ডেলিভারির সঙ্গে আপনার সরাসরি অবস্থান শেয়ার করছেন।",
  "Only this delivery’s donor, NGO, volunteer and the FoodBridge team can see it. Sharing stops when you leave this page, and positions are deleted when the delivery ends.": "শুধু এই ডেলিভারির দাতা, এনজিও, স্বেচ্ছাসেবক ও ফুডব্রিজ দল এটি দেখতে পান। এই পাতা ছেড়ে গেলে শেয়ার বন্ধ হয়, আর ডেলিভারি শেষ হলে অবস্থানের তথ্য মুছে ফেলা হয়।",
  "~{n} min": "~{n} মিনিট",
  "—": "—",
  "See all": "সব দেখুন",
  "Expires": "মেয়াদ",
  "Ready from {time}": "প্রস্তুত থাকবে {time} থেকে",
  "{qty} for {people}": "{people}-এর জন্য {qty}",
  "Apply": "প্রয়োগ করুন",
  "Reset": "রিসেট",
  "Clear filters": "ফিল্টার মুছুন",
  "Location": "অবস্থান",
  "Area": "এলাকা",
  "People": "মানুষ",
  "Notes": "নোট",
  "from {name}": "{name}-এর কাছ থেকে",
  "{d} from you": "আপনার থেকে {d}",
  "{d} from you (straight line)": "আপনার থেকে {d} (সরলরেখায়)",
  "Open in Maps": "ম্যাপে খুলুন",
  "Available": "পাওয়া যাচ্ছে",
  "Confirming…": "নিশ্চিত করা হচ্ছে…",
  "Withdrawing…": "প্রত্যাহার করা হচ্ছে…",
  "{n} meals served. Thank you!": "{n} বেলার খাবার পরিবেশিত হয়েছে। ধন্যবাদ!",
  "Distributed": "বিতরণ সম্পন্ন",
  "Donation": "দান",
  "Skip the volunteer login: play the volunteer’s part.": "স্বেচ্ছাসেবক হিসেবে লগইন না করেই তার ভূমিকা পালন করুন।",
  "Food information": "খাবারের তথ্য",
  "Ready for pickup": "সংগ্রহের জন্য প্রস্তুত",
  "Donor’s instructions": "দাতার নির্দেশনা",
  "Donor & location": "দাতা ও অবস্থান",
  "Pickup address": "সংগ্রহের ঠিকানা",
  "Preferred time": "পছন্দের সময়",
  "Allocated": "বরাদ্দ হয়েছে",
  "Rejected": "প্রত্যাখ্যাত",
  "Waiting for the donor to decide, or for suitable food.": "দাতার সিদ্ধান্ত বা উপযুক্ত খাবারের অপেক্ষায়।",
  "Suitable food found. Waiting for the NGO to accept.": "উপযুক্ত খাবার পাওয়া গেছে। এনজিওর গ্রহণের অপেক্ষায়।",
  "Accepted. Reserving the food and creating the pickup task.": "গৃহীত। খাবার সংরক্ষণ ও সংগ্রহের কাজ তৈরি করা হচ্ছে।",
  "Food reserved for the NGO and a volunteer pickup task created.": "এনজিওর জন্য খাবার সংরক্ষিত এবং স্বেচ্ছাসেবকের সংগ্রহের কাজ তৈরি হয়েছে।",
  "Passed on, or the food went to another NGO.": "বাদ দেওয়া হয়েছে, অথবা খাবার অন্য এনজিওর কাছে গেছে।",
  "The match was cancelled.": "মিলটি বাতিল করা হয়েছে।",
  "The food expired first.": "তার আগেই খাবারের মেয়াদ শেষ হয়ে গেছে।",
  "NGO requested it": "এনজিও অনুরোধ করেছে",
  "Matched by the system": "সিস্টেম মিলিয়েছে",
  "Allocated · pickup task created": "বরাদ্দ · সংগ্রহের কাজ তৈরি হয়েছে",
  "Declined / went elsewhere": "প্রত্যাখ্যাত / অন্যত্র গেছে",
  "Rejected by the NGO": "এনজিও প্রত্যাখ্যান করেছে",
  "No matching activity yet.": "এখনো মেলানোর কোনো কার্যক্রম নেই।",
  "Match status": "মিলের অবস্থা",
  "From": "থেকে",
  "requested": "অনুরোধ করা",
  "{n} matched": "{n} মিলেছে",
  "{n} delivered": "{n} পৌঁছেছে",
  "{n} remaining": "{n} বাকি",
  "{delivered} of {requested} meals delivered, {matched} matched": "{requested} বেলার মধ্যে {delivered} বেলার খাবার পৌঁছেছে, {matched} মিলেছে",
  "Any food": "যেকোনো খাবার",
  "{part} of {total}": "{total}-এর মধ্যে {part}",
  "Ready {time}": "প্রস্তুত {time}",
  "best before {time} ({relative})": "খাওয়ার শেষ সময় {time} ({relative})",
  "expires {relative}.": "মেয়াদ শেষ {relative}।",
  "needed by {time}": "দরকার {time}-এর মধ্যে",
  "under 1 km away": "১ কিমির কম দূরে",
  "{n} km away": "{n} কিমি দূরে",
  "in your area": "আপনার এলাকায়",
  "covers all {n} meals": "সব {n} বেলার খাবার পূরণ করে",
  "covers {a} of {b} meals": "{b} বেলার মধ্যে {a} বেলার খাবার পূরণ করে",
  "View full details": "সম্পূর্ণ বিবরণ দেখুন",
  "Closing…": "বন্ধ করা হচ্ছে…",
  "Views": "ভিউ",
  "Table": "টেবিল",
  "Search": "খুঁজুন",
  "Status": "অবস্থা",
  "Any status": "যেকোনো অবস্থা",
  "To": "পর্যন্ত",
  "Apply filters": "ফিল্টার প্রয়োগ করুন",
  "Showing the latest {n}. Narrow the filters to find older records.": "সর্বশেষ {n}টি দেখানো হচ্ছে। পুরোনো রেকর্ড খুঁজতে ফিল্টার আরও নির্দিষ্ট করুন।",
  "{n} result": "{n}টি ফলাফল",
  "{n} results": "{n}টি ফলাফল",
  "Food donated": "দান করা খাবার",
  "Food distributed": "বিতরণ করা খাবার",
  "Completed deliveries": "সম্পন্ন ডেলিভারি",
  "Expired food": "মেয়াদোত্তীর্ণ খাবার",
  "Food received": "পাওয়া খাবার",
  "Deliveries": "ডেলিভারি",
  "meals · {n} donations": "বেলার খাবার · {n}টি দান",
  "meals · {n} deliveries": "বেলার খাবার · {n}টি ডেলিভারি",
  "meals · {n} donations lost": "বেলার খাবার · {n}টি দান নষ্ট",
  "reported by NGOs": "এনজিওর দেওয়া হিসাব",
  "delivered or distributed": "পৌঁছেছে বা বিতরণ হয়েছে",
  "from your distribution records": "আপনার বিতরণের রেকর্ড থেকে",
  "No data for these filters.": "এই ফিল্টারে কোনো তথ্য নেই।",
  "Meals donated": "দান করা বেলার খাবার",
  "Meals distributed": "বিতরণ করা বেলার খাবার",
  "Month": "মাস",
  "By month": "মাস অনুযায়ী",
  "When the donation was posted.": "দান যখন পোস্ট করা হয়েছে।",
  "By food category": "খাবারের বিভাগ অনুযায়ী",
  "Your report": "আপনার রিপোর্ট",
  "Food delivered to your organisation and the meals you served. Useful for donors, funders and your own records.": "আপনার প্রতিষ্ঠানে পৌঁছানো খাবার এবং আপনার পরিবেশন করা বেলার খাবার। দাতা, অর্থদাতা ও নিজেদের রেকর্ডের জন্য কাজে লাগে।",
  "Dashboard": "ড্যাশবোর্ড",
  "Reason: {reason}": "কারণ: {reason}",
  "Call {name}": "{name}-কে ফোন করুন",
  "{label} photo": "{label}-এর ছবি",
  "Full name": "পুরো নাম",
  "Phone": "ফোন",
  "Password": "পাসওয়ার্ড",
  "Confirm password": "পাসওয়ার্ড নিশ্চিত করুন",
  "8+ characters with a letter and a number.": "অন্তত ৮ অক্ষর, এর মধ্যে একটি অক্ষর ও একটি সংখ্যা।",
  "01712 345678": "০১৭১২ ৩৪৫৬৭৮",
  "Choose one": "একটি বেছে নিন",
  "Save changes": "পরিবর্তন সংরক্ষণ করুন",
  "Log in": "লগ ইন",
  "Type": "ধরন",
  "Note": "নোট",
  "Photo": "ছবি",
  "JPG, PNG or WebP, up to 2 MB.": "JPG, PNG বা WebP, সর্বোচ্চ ২ MB।",
  "Welcome back": "আবার স্বাগতম",
  "Log in to your FoodBridge account.": "আপনার ফুডব্রিজ অ্যাকাউন্টে লগ ইন করুন।",
  "New to FoodBridge?": "ফুডব্রিজে নতুন?",
  "Create an account": "অ্যাকাউন্ট তৈরি করুন",
  "Create account": "অ্যাকাউন্ট তৈরি",
  "Already have an account?": "আগে থেকেই অ্যাকাউন্ট আছে?",
  "← Choose a different account type": "← অন্য ধরনের অ্যাকাউন্ট বেছে নিন",
  "Donor account": "দাতা অ্যাকাউন্ট",
  "NGO account": "এনজিও অ্যাকাউন্ট",
  "Volunteer account": "স্বেচ্ছাসেবক অ্যাকাউন্ট",
  "Start donating food": "খাবার দান শুরু করুন",
  "Takes about a minute. You can donate right after signing up.": "এক মিনিটের মতো সময় লাগে। নিবন্ধনের পরপরই দান করতে পারবেন।",
  "Receive surplus food": "উদ্বৃত্ত খাবার গ্রহণ করুন",
  "Register your organisation. Our team verifies every NGO, usually within one working day. You can browse donations meanwhile.": "আপনার প্রতিষ্ঠান নিবন্ধন করুন। আমাদের দল প্রতিটি এনজিও যাচাই করে, সাধারণত এক কর্মদিবসের মধ্যে। এর মধ্যে দানগুলো দেখতে পারবেন।",
  "Deliver food to people in need": "প্রয়োজনে থাকা মানুষের কাছে খাবার পৌঁছে দিন",
  "Pick up surplus food from donors and bring it to NGOs. Our team verifies every volunteer, usually within one working day.": "দাতাদের কাছ থেকে উদ্বৃত্ত খাবার সংগ্রহ করে এনজিওর কাছে পৌঁছে দিন। আমাদের দল প্রতিটি স্বেচ্ছাসেবককে যাচাই করে, সাধারণত এক কর্মদিবসের মধ্যে।",
  "Create your FoodBridge account": "আপনার ফুডব্রিজ অ্যাকাউন্ট তৈরি করুন",
  "Choose how you want to help. Each role has its own portal.": "কীভাবে সাহায্য করতে চান বেছে নিন। প্রতিটি ভূমিকার আলাদা পোর্টাল আছে।",
  "Restaurant, hotel, shop or household with surplus food to give.": "দেওয়ার মতো উদ্বৃত্ত খাবার আছে এমন রেস্তোরাঁ, হোটেল, দোকান বা পরিবার।",
  "Organisation that receives and distributes food. Needs verification.": "যে প্রতিষ্ঠান খাবার গ্রহণ ও বিতরণ করে। যাচাই প্রয়োজন।",
  "Pick up food from donors and deliver it to NGOs.": "দাতাদের কাছ থেকে খাবার নিয়ে এনজিওর কাছে পৌঁছে দিন।",
  "Coming soon": "শীঘ্রই আসছে",
  "Continue": "এগিয়ে যান",
  "Learn more": "আরও জানুন",
  "Account": "অ্যাকাউন্ট",
  "Donor type": "দাতার ধরন",
  "Verification": "যাচাই",
  "Under review": "যাচাই চলছে",
  "Availability": "প্রাপ্যতা",
  "Member since": "সদস্য হয়েছেন",
  "Organisation profile": "প্রতিষ্ঠানের প্রোফাইল",
  "Tell donors who you serve.": "আপনি কাদের সেবা দেন দাতাদের জানান।",
  "Only available volunteers are offered new pickups.": "শুধু ফাঁকা স্বেচ্ছাসেবকদেরই নতুন সংগ্রহের কাজ দেওয়া হয়।",
  "Basic information": "মৌলিক তথ্য",
  "Donors and NGOs see your name and phone during a pickup.": "সংগ্রহের সময় দাতা ও এনজিও আপনার নাম ও ফোন নম্বর দেখতে পান।",
  "Used to pre-fill pickup details on new donations.": "নতুন দানে সংগ্রহের তথ্য আগে থেকে পূরণ করতে ব্যবহৃত হয়।",
  "Only important updates about your food, requests and deliveries.": "শুধু আপনার খাবার, অনুরোধ ও ডেলিভারির গুরুত্বপূর্ণ আপডেট।",
  "Chat apps": "চ্যাট অ্যাপ",
  "Use FoodBridge from WhatsApp or Messenger. The website stays the place where everything is kept.": "হোয়াটসঅ্যাপ বা মেসেঞ্জার থেকে ফুডব্রিজ ব্যবহার করুন। সব তথ্য ওয়েবসাইটেই সংরক্ষিত থাকে।",
  "Use at least 8 characters with a letter and a number.": "অন্তত ৮ অক্ষর ব্যবহার করুন, এর মধ্যে একটি অক্ষর ও একটি সংখ্যা।",
  "Default pickup address": "ডিফল্ট সংগ্রহের ঠিকানা",
  "Usual pickup spot": "সাধারণ সংগ্রহের জায়গা",
  "Pre-fills the map pin on new donations, so NGOs and volunteers nearby find you.": "নতুন দানে মানচিত্রের পিন আগে থেকে বসিয়ে দেয়, যাতে কাছের এনজিও ও স্বেচ্ছাসেবকেরা আপনাকে খুঁজে পান।",
  "Current password": "বর্তমান পাসওয়ার্ড",
  "New password": "নতুন পাসওয়ার্ড",
  "Confirm new password": "নতুন পাসওয়ার্ড নিশ্চিত করুন",
  "Update password": "পাসওয়ার্ড হালনাগাদ করুন",
  "You always get in-app notifications. Also send important updates (matches, pickups, deliveries, expiry warnings) by:": "অ্যাপের ভেতরের নোটিফিকেশন সবসময় পাবেন। গুরুত্বপূর্ণ আপডেট (মিল, সংগ্রহ, ডেলিভারি, মেয়াদের সতর্কবার্তা) আরও পাঠানো হবে:",
  "Connected": "সংযুক্ত",
  "Coming soon: saved for when it’s connected": "শীঘ্রই আসছে: সংযুক্ত হলে ব্যবহারের জন্য সংরক্ষিত",
  "Save preferences": "পছন্দ সংরক্ষণ করুন",
  "Chat apps aren’t switched on for FoodBridge yet. You’ll be able to link WhatsApp and Messenger here once they are.": "ফুডব্রিজে চ্যাট অ্যাপ এখনো চালু হয়নি। চালু হলে এখানে হোয়াটসঅ্যাপ ও মেসেঞ্জার যুক্ত করতে পারবেন।",
  "Linked. You get key updates here and can post by chat.": "যুক্ত। এখানে মূল আপডেট পাবেন এবং চ্যাটে পোস্ট করতে পারবেন।",
  "Post food or requests and get key updates by chat.": "চ্যাটে খাবার বা অনুরোধ পোস্ট করুন এবং মূল আপডেট পান।",
  "Unlink": "সংযোগ বিচ্ছিন্ন করুন",
  "Couldn’t create a code. Please try again.": "কোড তৈরি করা যায়নি। আবার চেষ্টা করুন।",
  "New code": "নতুন কোড",
  "Link {app}": "{app} যুক্ত করুন",
  "Send this message to FoodBridge on {app} within {n} minutes:": "{n} মিনিটের মধ্যে {app}-এ ফুডব্রিজকে এই বার্তাটি পাঠান:",
  "Open {app}": "{app} খুলুন",
  "Never share this code. Refresh the page after linking.": "এই কোড কাউকে দেবেন না। যুক্ত করার পর পাতাটি রিফ্রেশ করুন।",
  "Updates": "আপডেট",
  "You have {n} unread update.": "আপনার {n}টি অপঠিত আপডেট আছে।",
  "You have {n} unread updates.": "আপনার {n}টি অপঠিত আপডেট আছে।",
  "You’re all caught up.": "সব আপডেট দেখা হয়ে গেছে।",
  "Mark all as read": "সব পঠিত হিসেবে চিহ্নিত করুন",
  "Filter notifications": "নোটিফিকেশন ফিল্টার করুন",
  "Unread": "অপঠিত",
  "Every kind": "সব ধরন",
  "(unread)": "(অপঠিত)",
  "Mark as unread": "অপঠিত হিসেবে চিহ্নিত করুন",
  "Mark as read": "পঠিত হিসেবে চিহ্নিত করুন",
  "Mark unread": "অপঠিত করুন",
  "Mark read": "পঠিত করুন",
  "Nothing here": "এখানে কিছু নেই",
  "No notifications yet": "এখনো কোনো নোটিফিকেশন নেই",
  "Try another filter.": "অন্য ফিল্টার দিয়ে চেষ্টা করুন।",
  "Updates about your food, requests and deliveries will appear here.": "আপনার খাবার, অনুরোধ ও ডেলিভারির আপডেট এখানে দেখা যাবে।",
  "At least 1 person.": "অন্তত ১ জন।",
  "Best-before must be after the prepared time.": "খাওয়ার শেষ সময় রান্না/প্রস্তুতের সময়ের পরে হতে হবে।",
  "Choose a food category.": "একটি খাবারের বিভাগ বেছে নিন।",
  "Choose a unit.": "একটি একক বেছে নিন।",
  "Choose a volunteer.": "একজন স্বেচ্ছাসেবক বেছে নিন।",
  "Choose the food condition.": "খাবারের অবস্থা বেছে নিন।",
  "Choose what describes you best.": "আপনাকে সবচেয়ে ভালো বোঝায় এমনটি বেছে নিন।",
  "Choose what describes your organisation.": "আপনার প্রতিষ্ঠানকে বোঝায় এমনটি বেছে নিন।",
  "Describe the food, e.g. “Chicken biryani”.": "খাবারের বিবরণ দিন, যেমন: “চিকেন বিরিয়ানি”।",
  "Describe the food.": "খাবারের বিবরণ দিন।",
  "Enter a quantity.": "পরিমাণ লিখুন।",
  "Enter a valid email address.": "সঠিক ইমেইল ঠিকানা লিখুন।",
  "Enter a valid phone number, e.g. 01712 345678.": "সঠিক ফোন নম্বর লিখুন, যেমন: ০১৭১২ ৩৪৫৬৭৮।",
  "Enter a whole number.": "পূর্ণ সংখ্যা লিখুন।",
  "Enter how many people you’ll feed.": "কতজনকে খাওয়াবেন লিখুন।",
  "Enter how many people you’ll serve.": "কতজনকে সেবা দেবেন লিখুন।",
  "Enter the area where food is needed, e.g. Mirpur, Dhaka.": "যে এলাকায় খাবার দরকার তা লিখুন, যেমন: মিরপুর, ঢাকা।",
  "Enter the area you can cover, e.g. Dhanmondi, Dhaka.": "যে এলাকায় কাজ করতে পারবেন তা লিখুন, যেমন: ধানমন্ডি, ঢাকা।",
  "Enter the area you serve, e.g. Mirpur, Dhaka.": "যে এলাকায় সেবা দেন তা লিখুন, যেমন: মিরপুর, ঢাকা।",
  "Enter the area you serve.": "যে এলাকায় সেবা দেন তা লিখুন।",
  "Enter the number of meals.": "বেলার খাবারের সংখ্যা লিখুন।",
  "Enter the quantity you need.": "প্রয়োজনীয় পরিমাণ লিখুন।",
  "Enter your business or organisation name.": "আপনার ব্যবসা বা প্রতিষ্ঠানের নাম লিখুন।",
  "Enter your current password.": "আপনার বর্তমান পাসওয়ার্ড লিখুন।",
  "Enter your organisation’s name.": "আপনার প্রতিষ্ঠানের নাম লিখুন।",
  "Enter your password.": "আপনার পাসওয়ার্ড লিখুন।",
  "Give donors and volunteers at least 30 minutes.": "দাতা ও স্বেচ্ছাসেবকদের অন্তত ৩০ মিনিট সময় দিন।",
  "Include at least one letter.": "অন্তত একটি অক্ষর রাখুন।",
  "Include at least one number.": "অন্তত একটি সংখ্যা রাখুন।",
  "Keep instructions under 500 characters.": "নির্দেশনা ৫০০ অক্ষরের মধ্যে রাখুন।",
  "Keep it under 80 characters.": "৮০ অক্ষরের মধ্যে রাখুন।",
  "Passwords do not match.": "পাসওয়ার্ড মেলেনি।",
  "Pickup must be before the best-before time.": "সংগ্রহের সময় খাওয়ার শেষ সময়ের আগে হতে হবে।",
  "Pickup time can’t be in the past.": "সংগ্রহের সময় অতীতে হতে পারে না।",
  "Please confirm the food-handling pledge.": "খাবার ব্যবস্থাপনার অঙ্গীকারটি নিশ্চিত করুন।",
  "Please confirm the food-safety pledge.": "খাদ্য-নিরাপত্তার অঙ্গীকারটি নিশ্চিত করুন।",
  "Please confirm the volunteer pledge.": "স্বেচ্ছাসেবকের অঙ্গীকারটি নিশ্চিত করুন।",
  "Please enter a full address.": "পূর্ণ ঠিকানা লিখুন।",
  "Please enter at least 2 characters.": "অন্তত ২টি অক্ষর লিখুন।",
  "Preferred time can’t be in the past.": "পছন্দের সময় অতীতে হতে পারে না।",
  "Prepared time can’t be in the future.": "রান্না/প্রস্তুতের সময় ভবিষ্যতে হতে পারে না।",
  "Quantity must be more than 0.": "পরিমাণ ০-এর বেশি হতে হবে।",
  "Requests can be at most 14 days ahead.": "অনুরোধ সর্বোচ্চ ১৪ দিন আগে করা যায়।",
  "Say how you confirmed it, e.g. “NGO called to confirm”.": "কীভাবে নিশ্চিত হয়েছেন লিখুন, যেমন: “এনজিও ফোন করে নিশ্চিত করেছে”।",
  "That looks too large — please check.": "এটি অনেক বেশি মনে হচ্ছে — একবার দেখে নিন।",
  "Use at least 8 characters.": "অন্তত ৮টি অক্ষর ব্যবহার করুন।",
  "Use at most 72 characters.": "সর্বোচ্চ ৭২টি অক্ষর ব্যবহার করুন।",
  "Enter the {label}.": "{label} লিখুন।",
  "best-before time": "খাওয়ার শেষ সময়",
  "pickup time": "সংগ্রহের সময়",
  "preferred pickup time": "পছন্দের সংগ্রহের সময়",
  "prepared time": "রান্না/প্রস্তুতের সময়",
  "time you need the food by": "যে সময়ের মধ্যে খাবার দরকার",
  "Food must stay safe for at least {n} more minutes to be picked up.": "সংগ্রহের জন্য খাবারটি আরও অন্তত {n} মিনিট নিরাপদ থাকতে হবে।",
  "An account with this email already exists. Try logging in.": "এই ইমেইলে আগে থেকেই একটি অ্যাকাউন্ট আছে। লগ ইন করে দেখুন।",
  "Current password is incorrect.": "বর্তমান পাসওয়ার্ড সঠিক নয়।",
  "Delivery completed. Thank you!": "ডেলিভারি সম্পন্ন। ধন্যবাদ!",
  "Delivery recorded.": "ডেলিভারি রেকর্ড করা হয়েছে।",
  "Donation updated.": "দান হালনাগাদ হয়েছে।",
  "Email or password is incorrect.": "ইমেইল বা পাসওয়ার্ড সঠিক নয়।",
  "Location updated.": "অবস্থান হালনাগাদ হয়েছে।",
  "Marked as distributed. Thank you!": "বিতরণ সম্পন্ন হিসেবে চিহ্নিত হয়েছে। ধন্যবাদ!",
  "Match cancelled. The food is available to other NGOs again.": "মিল বাতিল হয়েছে। খাবারটি আবার অন্য এনজিওগুলোর জন্য পাওয়া যাচ্ছে।",
  "Meals served recorded.": "পরিবেশিত বেলার খাবার রেকর্ড করা হয়েছে।",
  "Notification preferences saved.": "নোটিফিকেশনের পছন্দ সংরক্ষিত হয়েছে।",
  "Only delivered food can be marked as distributed.": "শুধু পৌঁছানো খাবারই বিতরণ সম্পন্ন হিসেবে চিহ্নিত করা যায়।",
  "Only food that has been picked up can be marked as delivered.": "শুধু সংগ্রহ করা খাবারই পৌঁছেছে হিসেবে চিহ্নিত করা যায়।",
  "Organisation profile saved.": "প্রতিষ্ঠানের প্রোফাইল সংরক্ষিত হয়েছে।",
  "Password updated. Other devices have been signed out.": "পাসওয়ার্ড হালনাগাদ হয়েছে। অন্য ডিভাইসগুলো থেকে সাইন আউট করা হয়েছে।",
  "Photo must be 2 MB or smaller.": "ছবি ২ MB বা তার ছোট হতে হবে।",
  "Pickup confirmed. Now deliver it to the NGO.": "সংগ্রহ নিশ্চিত হয়েছে। এখন এনজিওর কাছে পৌঁছে দিন।",
  "Pickup offered. They’ll be asked to accept or decline.": "সংগ্রহের কাজ প্রস্তাব করা হয়েছে। তাকে গ্রহণ বা প্রত্যাখ্যান করতে বলা হবে।",
  "Please fix the highlighted fields.": "চিহ্নিত ঘরগুলো ঠিক করুন।",
  "Profile saved.": "প্রোফাইল সংরক্ষিত হয়েছে।",
  "Switch to Available to accept new tasks.": "নতুন কাজ নিতে “ফাঁকা আছি” চালু করুন।",
  "That location doesn’t look right.": "অবস্থানটি সঠিক মনে হচ্ছে না।",
  "This account has been deactivated. Please contact support to reopen it.": "এই অ্যাকাউন্টটি নিষ্ক্রিয় করা হয়েছে। আবার চালু করতে সহায়তা দলের সঙ্গে যোগাযোগ করুন।",
  "This account is suspended. Please contact support.": "এই অ্যাকাউন্টটি স্থগিত। সহায়তা দলের সঙ্গে যোগাযোগ করুন।",
  "This donation can’t be completed yet.": "এই দানটি এখনো সম্পন্ন করা যাবে না।",
  "This item is no longer available. Please refresh the page.": "এটি আর পাওয়া যাচ্ছে না। পাতাটি রিফ্রেশ করুন।",
  "This request can’t be changed any more: food has already been accepted for it.": "এই অনুরোধ আর বদলানো যাবে না: এর জন্য খাবার ইতিমধ্যে গ্রহণ করা হয়েছে।",
  "This task can’t be marked as delivered yet.": "এই কাজটি এখনো পৌঁছেছে হিসেবে চিহ্নিত করা যাবে না।",
  "This task can’t be marked as picked up. It may have been cancelled.": "এই কাজটি সংগ্রহ হয়েছে হিসেবে চিহ্নিত করা যাচ্ছে না। হয়তো এটি বাতিল হয়েছে।",
  "This task went to another volunteer, or the food is no longer available.": "এই কাজটি অন্য স্বেচ্ছাসেবকের কাছে গেছে, অথবা খাবারটি আর পাওয়া যাচ্ছে না।",
  "Too many new accounts from this connection. Please try again in an hour.": "এই সংযোগ থেকে অনেকগুলো নতুন অ্যাকাউন্ট খোলা হয়েছে। এক ঘণ্টা পর আবার চেষ্টা করুন।",
  "Too many sign-in attempts. Please wait 15 minutes and try again.": "অনেকবার সাইন ইনের চেষ্টা হয়েছে। ১৫ মিনিট অপেক্ষা করে আবার চেষ্টা করুন।",
  "Use a JPG, PNG or WebP photo.": "JPG, PNG বা WebP ছবি ব্যবহার করুন।",
  "Your NGO must be verified before you can accept food.": "খাবার গ্রহণের আগে আপনার এনজিও যাচাই হতে হবে।",
  "Your NGO must be verified before you can post food requests.": "খাবারের অনুরোধ পোস্ট করার আগে আপনার এনজিও যাচাই হতে হবে।",
  "Your NGO must be verified before you can request food.": "খাবারের অনুরোধ করার আগে আপনার এনজিও যাচাই হতে হবে।",
  "Your account must be verified before you can accept tasks.": "কাজ নেওয়ার আগে আপনার অ্যাকাউন্ট যাচাই হতে হবে।",
  "Choose an active, verified volunteer.": "একজন সক্রিয়, যাচাই করা স্বেচ্ছাসেবক বেছে নিন।",
  "Only donations that haven’t been picked up yet can be edited.": "শুধু যেসব দান এখনো সংগ্রহ করা হয়নি সেগুলোই সম্পাদনা করা যায়।",
  "Only donor accounts can post donations.": "শুধু দাতা অ্যাকাউন্ট দান পোস্ট করতে পারে।",
  "Only verified NGO accounts can post food requests.": "শুধু যাচাই করা এনজিও অ্যাকাউন্ট খাবারের অনুরোধ পোস্ট করতে পারে।",
  "Preferred time must be before the food’s best-before time.": "পছন্দের সময় খাবারের খাওয়ার শেষ সময়ের আগে হতে হবে।",
  "Sorry, this food was just taken or has expired. We’ll look for another match.": "দুঃখিত, খাবারটি এইমাত্র অন্য কেউ নিয়েছে বা মেয়াদ শেষ হয়েছে। আমরা আরেকটি মিল খুঁজব।",
  "The best-before time must be in the future.": "খাওয়ার শেষ সময় ভবিষ্যতে হতে হবে।",
  "The food has already been picked up, so the match can’t be cancelled now.": "খাবার ইতিমধ্যে সংগ্রহ করা হয়েছে, তাই এখন মিল বাতিল করা যাবে না।",
  "This donation is no longer available.": "এই দানটি আর পাওয়া যাচ্ছে না।",
  "This donation no longer exists.": "এই দানটি আর নেই।",
  "This food is on a safety hold. Clear the hold first.": "এই খাবার নিরাপত্তার কারণে স্থগিত। আগে স্থগিতাদেশ তুলে নিন।",
  "This food is past its best-before time.": "এই খাবারের খাওয়ার শেষ সময় পেরিয়ে গেছে।",
  "This food is paused for a food-safety check and can’t be allocated right now.": "খাদ্য-নিরাপত্তা যাচাইয়ের জন্য এই খাবার স্থগিত, তাই এখন বরাদ্দ করা যাবে না।",
  "This match can’t be cancelled any more.": "এই মিল আর বাতিল করা যাবে না।",
  "This match is no longer available.": "এই মিল আর পাওয়া যাচ্ছে না।",
  "This pickup already has a volunteer or is no longer waiting for one.": "এই সংগ্রহের কাজে ইতিমধ্যে একজন স্বেচ্ছাসেবক আছেন, অথবা আর কারও অপেক্ষায় নেই।",
  "This request is no longer open.": "এই অনুরোধটি আর খোলা নেই।",
  "Your NGO is still being verified. You can post food requests once it’s approved.": "আপনার এনজিও এখনো যাচাই করা হচ্ছে। অনুমোদনের পর খাবারের অনুরোধ পোস্ট করতে পারবেন।",
  "You’ve already requested this donation.": "আপনি ইতিমধ্যে এই দানের অনুরোধ করেছেন।",
  "Volunteer released by admin": "অ্যাডমিন স্বেচ্ছাসেবককে সরিয়েছেন",
  "Reassigned by FoodBridge": "ফুডব্রিজ নতুন করে নির্ধারণ করেছে",
  "Volunteer unavailable": "স্বেচ্ছাসেবক ব্যস্ত",
  "Best-before time passed.": "খাওয়ার শেষ সময় পেরিয়ে গেছে।",
  "Confirmed by NGO": "এনজিও নিশ্চিত করেছে",
  "We couldn’t load this page. Your data is safe — please try again.": "পাতাটি লোড করা যায়নি। আপনার তথ্য নিরাপদ আছে — আবার চেষ্টা করুন।",
  "Try again": "আবার চেষ্টা করুন",
  "Go home": "হোমে যান",
  "Page not found": "পাতাটি পাওয়া যায়নি",
  "The page you’re looking for doesn’t exist or you don’t have access to it.": "আপনি যে পাতাটি খুঁজছেন তা নেই, অথবা সেটি দেখার অনুমতি আপনার নেই।",
  "Back to home": "হোমে ফিরুন",
  "Ask FoodBridge": "ফুডব্রিজকে জিজ্ঞাসা করুন",
  "FoodBridge assistant": "ফুডব্রিজ সহকারী",
  "AI assistant · can make mistakes · never changes your data": "এআই সহকারী · ভুল করতে পারে · আপনার তথ্য কখনো বদলায় না",
  "Ask FoodBridge · AI can make mistakes · never changes your data": "ফুডব্রিজকে জিজ্ঞাসা করুন · এআই ভুল করতে পারে · আপনার তথ্য কখনো বদলায় না",
  "Help mode (AI not configured)": "সহায়তা মোড (এআই চালু নেই)",
  "New chat": "নতুন চ্যাট",
  "Open full screen": "পূর্ণ পর্দায় খুলুন",
  "Full screen": "পূর্ণ পর্দা",
  "Exit full screen": "পূর্ণ পর্দা থেকে বের হন",
  "Close assistant": "সহকারী বন্ধ করুন",
  "How can I help?": "কীভাবে সাহায্য করতে পারি?",
  "I can answer questions about FoodBridge, fill in a donation for you, and sort out what needs your attention. Try:": "আমি ফুডব্রিজ সম্পর্কে প্রশ্নের উত্তর দিতে পারি, আপনার হয়ে দানের ফর্ম পূরণ করতে পারি এবং কোন কাজে আপনার মনোযোগ দরকার তা গুছিয়ে দিতে পারি। চেষ্টা করুন:",
  "I can answer questions about FoodBridge, fill in a food request for you, and sort out what needs your attention. Try:": "আমি ফুডব্রিজ সম্পর্কে প্রশ্নের উত্তর দিতে পারি, আপনার হয়ে খাবারের অনুরোধ পূরণ করতে পারি এবং কোন কাজে আপনার মনোযোগ দরকার তা গুছিয়ে দিতে পারি। চেষ্টা করুন:",
  "I can answer questions about FoodBridge and sort out what needs your attention. Try:": "আমি ফুডব্রিজ সম্পর্কে প্রশ্নের উত্তর দিতে পারি এবং কোন কাজে আপনার মনোযোগ দরকার তা গুছিয়ে দিতে পারি। চেষ্টা করুন:",
  "What should I do next?": "এরপর আমার কী করা উচিত?",
  "I have 20 plates of chicken biryani cooked an hour ago": "এক ঘণ্টা আগে রান্না করা ২০ প্লেট চিকেন বিরিয়ানি আছে",
  "What are the food-safety rules?": "খাদ্য-নিরাপত্তার নিয়মগুলো কী?",
  "We need rice meals for 40 children tonight in Mirpur": "আজ রাতে মিরপুরে ৪০ জন শিশুর জন্য ভাতের খাবার দরকার",
  "How does matching work?": "মেলানো কীভাবে কাজ করে?",
  "How do I accept or decline a pickup?": "সংগ্রহের কাজ কীভাবে গ্রহণ বা প্রত্যাখ্যান করব?",
  "How does live location work?": "সরাসরি অবস্থান কীভাবে কাজ করে?",
  "What needs my attention?": "কোন কাজে আমার মনোযোগ দরকার?",
  "Summarise my alerts": "আমার সতর্কবার্তাগুলোর সারসংক্ষেপ দিন",
  "How can I pause unsafe food?": "অনিরাপদ খাবার কীভাবে স্থগিত করব?",
  "From: {list}": "সূত্র: {list}",
  "Thinking…": "ভাবছি…",
  "Message": "বার্তা",
  "Ask a question or describe your food…": "প্রশ্ন করুন বা আপনার খাবারের বিবরণ দিন…",
  "Send": "পাঠান",
  "Donation draft": "দানের খসড়া",
  "Food request draft": "খাবারের অনুরোধের খসড়া",
  "Open the form with these details": "এই তথ্য দিয়ে ফর্ম খুলুন",
  "You check everything and post it yourself.": "সবকিছু যাচাই করে আপনি নিজেই পোস্ট করবেন।",
  "Instructions": "নির্দেশনা",
  "Prepared (min ago)": "রান্না/প্রস্তুত (কত মিনিট আগে)",
  "Best before (hours from now)": "খাওয়ার শেষ সময় (এখন থেকে কত ঘণ্টা)",
  "Pickup in (min)": "সংগ্রহ (কত মিনিট পরে)",
  "Needed in (hours)": "দরকার (কত ঘণ্টা পরে)",
  "food type": "খাবারের ধরন",
  "category": "বিভাগ",
  "quantity": "পরিমাণ",
  "condition": "অবস্থা",
  "best-before": "খাওয়ার শেষ সময়",
  "pickup address": "সংগ্রহের ঠিকানা",
  "people to serve": "কতজনকে খাওয়াবেন",
  "area": "এলাকা",
  "needed-by time": "যে সময়ের মধ্যে দরকার",
  "Here’s what needs your attention:": "যেসব বিষয়ে আপনার মনোযোগ দরকার:",
  "You’re all caught up: nothing needs your attention right now.": "সব ঠিক আছে: এখন কোনো কিছুতে আপনার মনোযোগ দরকার নেই।",
  "Review {n} NGO request for “{food}”": "“{food}”-এর জন্য {n}টি এনজিও অনুরোধ দেখুন",
  "Review {n} NGO requests for “{food}”": "“{food}”-এর জন্য {n}টি এনজিও অনুরোধ দেখুন",
  "Accept one NGO so a volunteer can collect it.": "একটি এনজিওর অনুরোধ গ্রহণ করুন, যাতে একজন স্বেচ্ছাসেবক এটি সংগ্রহ করতে পারেন।",
  "“{food}” is expiring soon": "“{food}”-এর মেয়াদ শীঘ্রই শেষ হবে",
  "“{food}” is paused for a safety check": "নিরাপত্তা যাচাইয়ের জন্য “{food}” স্থগিত",
  "Check the note from FoodBridge, or cancel it if the food isn’t safe.": "ফুডব্রিজের নোট দেখুন, অথবা খাবার নিরাপদ না হলে বাতিল করুন।",
  "“{food}” is being delivered": "“{food}” পৌঁছানো হচ্ছে",
  "Follow it on the map.": "মানচিত্রে অনুসরণ করুন।",
  "Post surplus food": "উদ্বৃত্ত খাবার পোস্ট করুন",
  "Tell me what you have and I’ll fill in the donation form.": "আপনার কাছে কী আছে বলুন, আমি দানের ফর্ম পূরণ করে দেব।",
  "Accept or reject the match “{food}”": "“{food}”-এর মিল গ্রহণ বা প্রত্যাখ্যান করুন",
  "From {donor}. Expires {left}.": "{donor}-এর কাছ থেকে। মেয়াদ: {left}।",
  "“{food}” is on its way": "“{food}” পথে আছে",
  "Confirm when it arrives.": "পৌঁছালে নিশ্চিত করুন।",
  "Mark “{food}” as distributed": "“{food}” বিতরণ সম্পন্ন হিসেবে চিহ্নিত করুন",
  "Enter how many meals you served.": "কত বেলার খাবার পরিবেশন করেছেন লিখুন।",
  "No food found yet for “{food}”": "“{food}”-এর জন্য এখনো খাবার পাওয়া যায়নি",
  "your request": "আপনার অনুরোধ",
  "{n} meals still needed. Try any food type or a later time.": "এখনো {n} বেলার খাবার দরকার। যেকোনো খাবার বা পরের কোনো সময় দিয়ে চেষ্টা করুন।",
  "Your NGO is awaiting verification": "আপনার এনজিও যাচাইয়ের অপেক্ষায়",
  "You can request food once FoodBridge verifies you.": "ফুডব্রিজ যাচাই করার পর আপনি খাবারের অনুরোধ করতে পারবেন।",
  "Your account is awaiting verification": "আপনার অ্যাকাউন্ট যাচাইয়ের অপেক্ষায়",
  "Complete your profile meanwhile.": "এর মধ্যে আপনার প্রোফাইল সম্পূর্ণ করুন।",
  "Pickup assigned to you: “{food}”": "আপনাকে দেওয়া সংগ্রহের কাজ: “{food}”",
  "Accept or decline soon; it moves on if you don’t reply.": "দ্রুত গ্রহণ বা প্রত্যাখ্যান করুন; উত্তর না দিলে এটি অন্যের কাছে চলে যাবে।",
  "Your task: “{food}”": "আপনার কাজ: “{food}”",
  "Collect it and confirm pickup.": "এটি সংগ্রহ করে সংগ্রহ নিশ্চিত করুন।",
  "Start the delivery.": "ডেলিভারি শুরু করুন।",
  "Deliver it and confirm delivery.": "এটি পৌঁছে দিয়ে ডেলিভারি নিশ্চিত করুন।",
  "{n} open pickup nearby": "কাছাকাছি {n}টি খোলা সংগ্রহের কাজ",
  "{n} open pickups nearby": "কাছাকাছি {n}টি খোলা সংগ্রহের কাজ",
  "Anyone can take these.": "যে কেউ এগুলো নিতে পারেন।",
  "You’re offline": "আপনি অফলাইনে আছেন",
  "Switch to Available to get pickups.": "সংগ্রহের কাজ পেতে “ফাঁকা আছি” চালু করুন।",
  "Set your location": "আপনার অবস্থান সেট করুন",
  "So the nearest pickups come to you first.": "যাতে সবচেয়ে কাছের সংগ্রহের কাজ আগে আপনার কাছে আসে।",
  "Verify {n} partner account": "{n}টি অংশীদার অ্যাকাউন্ট যাচাই করুন",
  "Verify {n} partner accounts": "{n}টি অংশীদার অ্যাকাউন্ট যাচাই করুন",
  "NGOs and volunteers waiting for review.": "যাচাইয়ের অপেক্ষায় থাকা এনজিও ও স্বেচ্ছাসেবক।",
  "Finish the safety check for “{food}”": "“{food}”-এর নিরাপত্তা যাচাই শেষ করুন",
  "“{food}” expires {left}": "“{food}”-এর মেয়াদ: {left}",
  "{a} left": "{a} বাকি",
  "{a} min": "{a} মিনিট",
  "{h} h {m} min": "{h} ঘণ্টা {m} মিনিট",
  "{h} h": "{h} ঘণ্টা",
  "expired {a} ago": "{a} আগে মেয়াদ শেষ",
  "Today": "আজ",
  "Yesterday": "গতকাল",
  "Previous 7 days": "আগের ৭ দিন",
  "Previous 30 days": "আগের ৩০ দিন",
  "Older": "আরও পুরোনো",
  "Chat history": "চ্যাটের ইতিহাস",
  "Back to FoodBridge": "ফুডব্রিজে ফিরুন",
  "Your chats will appear here.": "আপনার চ্যাটগুলো এখানে দেখা যাবে।",
  "Delete “{title}”?": "“{title}” মুছে ফেলবেন?",
  "Delete all your chats? This can’t be undone.": "আপনার সব চ্যাট মুছে ফেলবেন? এটি আর ফেরানো যাবে না।",
  "Delete all chats": "সব চ্যাট মুছুন",
  "Close chat history": "চ্যাটের ইতিহাস বন্ধ করুন",
  "Open chat history": "চ্যাটের ইতিহাস খুলুন",
  "Chat name": "চ্যাটের নাম",
  "Rename “{title}”": "“{title}”-এর নাম বদলান",
  "Delete “{title}”": "“{title}” মুছুন",
  "Something went wrong.": "কিছু একটা ভুল হয়েছে।",
  "Something went wrong. Please try again.": "কিছু একটা ভুল হয়েছে। আবার চেষ্টা করুন।",
  "Please type a message (up to 2000 characters).": "একটি বার্তা লিখুন (সর্বোচ্চ ২০০০ অক্ষর)।",
  "You’re sending messages quickly. Please wait a moment.": "আপনি খুব দ্রুত বার্তা পাঠাচ্ছেন। একটু অপেক্ষা করুন।",
  "Sorry, I couldn’t work that out. Please try again.": "দুঃখিত, বুঝতে পারিনি। আবার চেষ্টা করুন।",
  "Choose a volunteer": "একজন স্বেচ্ছাসেবক বেছে নিন",
  "Portal": "পোর্টাল",
  "Main": "প্রধান",
  "Requested": "অনুরোধ করা হয়েছে",
  "Assistant": "সহকারী",
  "FoodBridge — Share surplus food, feed people": "ফুডব্রিজ — উদ্বৃত্ত খাবার ভাগ করুন, মানুষকে খাওয়ান",

  // Landing-page helper (visitor assistant)
  "Donate with our helper": "সহকারীর সাহায্যে দান করুন",
  "FoodBridge Helper": "ফুডব্রিজ সহকারী",
  "AI assistant · helps you donate food": "এআই সহকারী · খাবার দানে সাহায্য করে",
  "Start over": "নতুন করে শুরু",
  "Close chat": "চ্যাট বন্ধ করুন",
  "{a} of {b}": "{b}-এর মধ্যে {a}",
  "Hello! 👋 I’m the FoodBridge Helper. Have some food left over? Tell me about it and I’ll fill in the donation form for you, one question at a time. You can also ask me anything about FoodBridge.": "আসসালামু আলাইকুম! 👋 আমি ফুডব্রিজ সহকারী। কিছু খাবার বেঁচে গেছে? আমাকে বলুন, আমি একে একে প্রশ্ন করে আপনার জন্য দানের ফর্মটি পূরণ করে দেব। ফুডব্রিজ নিয়ে যেকোনো প্রশ্নও করতে পারেন।",
  "Type your message…": "আপনার বার্তা লিখুন…",
  "AI can make mistakes. You check the form before anything is posted.": "এআই ভুল করতে পারে। কিছু পোস্ট হওয়ার আগে আপনি নিজে ফর্মটি দেখে নেবেন।",
  "{n} min": "{n} মিনিট",
  "{n} h": "{n} ঘণ্টা",
  "Your donation form is ready": "আপনার দানের ফর্ম প্রস্তুত",
  "Open my donation form": "আমার দানের ফর্ম খুলুন",
  "Log in with a donor account to post food.": "খাবার পোস্ট করতে দাতা অ্যাকাউন্ট দিয়ে লগ ইন করুন।",
  "Create a free donor account": "বিনামূল্যে দাতা অ্যাকাউন্ট খুলুন",
  "I already have an account": "আমার অ্যাকাউন্ট আছে",
  "I have leftover food to donate": "আমার কিছু খাবার বেঁচে গেছে, দান করতে চাই",
  "How does FoodBridge work?": "ফুডব্রিজ কীভাবে কাজ করে?",
  "We are an NGO. How do we get food?": "আমরা একটি এনজিও। আমরা কীভাবে খাবার পাব?",
  "How can I volunteer?": "আমি কীভাবে স্বেচ্ছাসেবক হতে পারি?",
  "Amount": "পরিমাণ",
  "Kind": "ধরন",
  "Good for": "ভালো থাকবে",
  "Pickup in": "সংগ্রহ হবে",
  "Pickup at": "সংগ্রহের ঠিকানা",
  "Please type a message (up to 1000 characters).": "একটি বার্তা লিখুন (১০০০ অক্ষর পর্যন্ত)।",
  "Lovely! What food would you like to donate? (e.g. chicken biryani, bread, rice and dal)": "চমৎকার! কোন খাবার দান করতে চান? (যেমন: চিকেন বিরিয়ানি, রুটি, ভাত-ডাল)",
  "How much is there? (e.g. 20 plates or 5 kg)": "কতটুকু আছে? (যেমন: ২০ প্লেট বা ৫ কেজি)",
  "Is that in plates, kg, packets, boxes, litres or pieces?": "এটা কিসে মাপা: প্লেট, কেজি, প্যাকেট, বক্স, লিটার নাকি পিস?",
  "What kind of food is it: cooked, bakery, packaged, raw, fruits & vegetables, dairy or other?": "খাবারটা কোন ধরনের: রান্না করা, বেকারি, প্যাকেটজাত, কাঁচা, ফল ও সবজি, দুগ্ধজাত নাকি অন্য কিছু?",
  "When was it cooked or prepared? (e.g. 1 hour ago)": "এটা কখন রান্না বা তৈরি হয়েছিল? (যেমন: ১ ঘণ্টা আগে)",
  "How is it now: fresh, good, or should it be eaten soon?": "এখন খাবারটা কেমন: টাটকা, ভালো, নাকি তাড়াতাড়ি খেয়ে ফেলা দরকার?",
  "For how many more hours will it stay good to eat? (e.g. 4 hours)": "আর কত ঘণ্টা খাওয়ার উপযোগী থাকবে? (যেমন: ৪ ঘণ্টা)",
  "When can a volunteer pick it up? (e.g. in 30 minutes)": "স্বেচ্ছাসেবক কখন নিতে আসতে পারবেন? (যেমন: ৩০ মিনিট পর)",
  "What’s the pickup address or area? (e.g. House 12, Road 5, Mirpur 10, Dhaka)": "কোন ঠিকানা বা এলাকা থেকে নিতে হবে? (যেমন: বাসা ১২, রোড ৫, মিরপুর ১০, ঢাকা)",
  "Thank you so much! 🙏 Your donation form is ready. Tap the button below, log in or create a free donor account (it takes a minute), check the details and post it. A verified NGO nearby will confirm it and a volunteer will collect it from you.": "অনেক অনেক ধন্যবাদ! 🙏 আপনার দানের ফর্ম প্রস্তুত। নিচের বোতামে চাপুন, লগ ইন করুন বা বিনামূল্যে দাতা অ্যাকাউন্ট খুলুন (এক মিনিট লাগবে), তথ্যগুলো দেখে নিয়ে পোস্ট করুন। কাছের একটি যাচাই করা এনজিও তা নিশ্চিত করবে আর একজন স্বেচ্ছাসেবক আপনার কাছ থেকে খাবার নিয়ে যাবেন।",
  "FoodBridge connects restaurants, hotels, shops and households with NGOs and volunteers to rescue surplus food and deliver it to people in need.": "ফুডব্রিজ রেস্তোরাঁ, হোটেল, দোকান ও বাসাবাড়িকে এনজিও ও স্বেচ্ছাসেবকদের সঙ্গে যুক্ত করে, যাতে উদ্বৃত্ত খাবার উদ্ধার করে প্রয়োজনে থাকা মানুষের কাছে পৌঁছানো যায়।",
};
