export const DONOR: Record<string, string> = {
  "Donor dashboard": "দাতার ড্যাশবোর্ড",
  "Welcome to FoodBridge — your donor account is ready": "ফুডব্রিজে স্বাগতম — আপনার দাতা অ্যাকাউন্ট প্রস্তুত",
  "Post your first donation below. It takes about a minute.": "নিচে আপনার প্রথম দান পোস্ট করুন। মাত্র এক মিনিটের মতো সময় লাগে।",
  "Thank you for sharing food with your community.": "আপনার এলাকার মানুষের সঙ্গে খাবার ভাগ করে নেওয়ার জন্য ধন্যবাদ।",
  "View my donations": "আমার দানগুলো দেখুন",
  "Meals saved": "বাঁচানো বেলার খাবার",
  "Counted from completed donations. About 400 g of food is one meal.": "সম্পন্ন দান থেকে গোনা। প্রায় ৪০০ গ্রাম খাবার এক বেলার খাবার।",
  "NGOs are asking for your food": "এনজিওগুলো আপনার খাবার চাইছে",
  "{n} request is waiting for you to accept:": "{n}টি অনুরোধ আপনার সম্মতির অপেক্ষায়:",
  "{n} requests are waiting for you to accept:": "{n}টি অনুরোধ আপনার সম্মতির অপেক্ষায়:",
  "{n} donations have NGO requests waiting for you to accept.": "{n}টি দানের জন্য এনজিওর অনুরোধ আপনার সম্মতির অপেক্ষায়।",
  "“{food}” expires within an hour and hasn’t been picked up yet.": "“{food}”-এর মেয়াদ এক ঘণ্টার মধ্যে শেষ হবে, এখনো সংগ্রহ করা হয়নি।",
  "{n} donations expire within an hour and haven’t been picked up yet.": "{n}টি দানের মেয়াদ এক ঘণ্টার মধ্যে শেষ হবে, এখনো সংগ্রহ করা হয়নি।",
  "Active donations": "সক্রিয় দান",
  "Waiting for pickup or on the way": "সংগ্রহের অপেক্ষায় বা পথে",
  "Delivered and served": "পৌঁছে পরিবেশিত",
  "Total posted": "মোট পোস্ট",
  "All donations you’ve shared": "আপনার শেয়ার করা সব দান",
  "Your impact over time": "সময়ের সঙ্গে আপনার অবদান",
  "Meals are counted when your food reaches an NGO.": "আপনার খাবার এনজিওর কাছে পৌঁছালে বেলার খাবার গোনা হয়।",
  "Meals delivered from your food": "আপনার খাবার থেকে পৌঁছানো বেলার খাবার",
  "Donations posted": "পোস্ট করা দান",
  "Meals rescued": "উদ্ধার করা বেলার খাবার",
  "Tap a donation to see its live status.": "সরাসরি অবস্থা দেখতে একটি দানে চাপ দিন।",
  "No active donations": "কোনো সক্রিয় দান নেই",
  "When you have extra food, post it here and a nearby NGO will pick it up.": "বাড়তি খাবার থাকলে এখানে পোস্ট করুন, কাছের একটি এনজিও তা সংগ্রহ করবে।",
  "Recently completed": "সম্প্রতি সম্পন্ন",
  "Completed donations will appear here.": "সম্পন্ন দানগুলো এখানে দেখা যাবে।",
  "Before you donate": "দান করার আগে",
  "A quick food-safety check keeps everyone safe.": "ছোট্ট একটি খাদ্য-নিরাপত্তা যাচাই সবাইকে নিরাপদ রাখে।",
  "Food is cooked or packed today and stored covered": "খাবার আজই রান্না বা প্যাক করা এবং ঢেকে রাখা",
  "Hot food kept hot, cold food kept cold": "গরম খাবার গরম, ঠান্ডা খাবার ঠান্ডা রাখা",
  "No food that’s been served on plates or half-eaten": "প্লেটে পরিবেশন করা বা আধখাওয়া কোনো খাবার নয়",
  "Allergens (nuts, dairy…) noted in instructions": "অ্যালার্জির উপাদান (বাদাম, দুধ…) নির্দেশনায় উল্লেখ করা",
  "Every donation you’ve posted, with its live status.": "আপনার পোস্ট করা প্রতিটি দান, সরাসরি অবস্থাসহ।",
  "Filter donations": "দান ফিল্টার করুন",
  "Showing {n} donation": "{n}টি দান দেখানো হচ্ছে",
  "Showing {n} donations": "{n}টি দান দেখানো হচ্ছে",
  "No donations yet": "এখনো কোনো দান নেই",
  "No completed donations": "কোনো সম্পন্ন দান নেই",
  "Donations you post will show up here with their live status.": "আপনার পোস্ট করা দান এখানে সরাসরি অবস্থাসহ দেখা যাবে।",
  "New donation": "নতুন দান",
  "Tell us what you have. It takes about a minute, and a nearby NGO is notified right away.": "আপনার কাছে কী আছে জানান। এক মিনিটের মতো সময় লাগে, আর কাছের একটি এনজিও সঙ্গে সঙ্গে খবর পায়।",
  "What happens next": "এরপর যা হয়",
  "NGOs nearby are notified": "কাছের এনজিওগুলো খবর পায়",
  "Verified NGOs see your donation right away.": "যাচাই করা এনজিওগুলো সঙ্গে সঙ্গে আপনার দান দেখতে পায়।",
  "An NGO accepts": "একটি এনজিও গ্রহণ করে",
  "You get a notification with their name and phone.": "আপনি তাদের নাম ও ফোন নম্বরসহ একটি নোটিফিকেশন পান।",
  "A volunteer picks it up": "একজন স্বেচ্ছাসেবক সংগ্রহ করেন",
  "They arrive at your pickup time and address.": "তিনি আপনার দেওয়া সময়ে ও ঠিকানায় আসেন।",
  "Meals are served": "খাবার পরিবেশন করা হয়",
  "Your dashboard shows the meals you saved.": "আপনার ড্যাশবোর্ডে বাঁচানো বেলার খাবারের হিসাব দেখা যায়।",
  "Tips for a quick match": "দ্রুত মেলানোর পরামর্শ",
  "Be specific: “Chicken biryani”, not just “food”.": "নির্দিষ্ট করে লিখুন: শুধু “খাবার” নয়, “চিকেন বিরিয়ানি”।",
  "Give a realistic best-before time.": "বাস্তবসম্মত খাওয়ার শেষ সময় দিন।",
  "A photo helps NGOs decide faster.": "একটি ছবি এনজিওকে দ্রুত সিদ্ধান্ত নিতে সাহায্য করে।",
  "Keep your phone nearby for the pickup call.": "সংগ্রহের ফোনের জন্য ফোন কাছে রাখুন।",
  "Filled in by the assistant": "সহকারী পূরণ করেছে",
  "Please check every field (especially quantity and times) before posting.": "পোস্ট করার আগে প্রতিটি ঘর (বিশেষ করে পরিমাণ ও সময়) যাচাই করুন।",
  "What food are you donating?": "আপনি কী খাবার দান করছেন?",
  "Food type": "খাবারের ধরন",
  "e.g. Chicken biryani, bread loaves, mixed vegetables": "যেমন: চিকেন বিরিয়ানি, পাউরুটি, মিশ্র সবজি",
  "Choose a category": "একটি বিভাগ বেছে নিন",
  "e.g. 20": "যেমন: ২০",
  "Unit": "একক",
  "How is the food?": "খাবারের অবস্থা কেমন?",
  "When? (food safety)": "কখন? (খাদ্য নিরাপত্তা)",
  "Food-safety rules": "খাদ্য-নিরাপত্তার নিয়ম",
  "Food must stay safe for at least {n} more minutes when you post it.": "পোস্ট করার সময় খাবারটি আরও অন্তত {n} মিনিট নিরাপদ থাকতে হবে।",
  "Best-before limits after preparation: cooked meals {cooked} h, dairy {dairy} h, raw ingredients {raw} h, bakery {bakery} days, fruits & vegetables {fruit} days, packaged food {packaged} days, other {other} h.": "রান্না/প্রস্তুতের পর খাওয়ার শেষ সময়ের সীমা: রান্না করা খাবার {cooked} ঘণ্টা, দুগ্ধজাত {dairy} ঘণ্টা, কাঁচা উপকরণ {raw} ঘণ্টা, বেকারি {bakery} দিন, ফল ও সবজি {fruit} দিন, প্যাকেটজাত খাবার {packaged} দিন, অন্যান্য {other} ঘণ্টা।",
  "“Consume soon” food can be listed for at most {n} hours.": "“দ্রুত খেতে হবে” খাবার সর্বোচ্চ {n} ঘণ্টার জন্য তালিকাভুক্ত করা যায়।",
  "Food is marked “Expiring soon” in its last {n} minutes and removed from matching once it expires.": "শেষ {n} মিনিটে খাবারটি “শীঘ্রই মেয়াদ শেষ” হিসেবে চিহ্নিত হয় এবং মেয়াদ শেষ হলে মেলানো থেকে সরিয়ে দেওয়া হয়।",
  "FoodBridge can pause (flag) a donation for a safety check or withdraw it when its safety details are incomplete or doubtful.": "নিরাপত্তার তথ্য অসম্পূর্ণ বা সন্দেহজনক হলে ফুডব্রিজ যাচাইয়ের জন্য দান স্থগিত (ফ্ল্যাগ) বা প্রত্যাহার করতে পারে।",
  "Pickup from": "সংগ্রহ শুরুর সময়",
  "Earliest time food is ready.": "খাবার প্রস্তুত হওয়ার সবচেয়ে আগের সময়।",
  "Must be eaten by this time.": "এই সময়ের মধ্যে খেতে হবে।",
  "Where to pick up?": "কোথা থেকে সংগ্রহ করতে হবে?",
  "House, road, area, landmark": "বাড়ি, রাস্তা, এলাকা, চেনার মতো জায়গা",
  "Pickup spot on the map": "মানচিত্রে সংগ্রহের জায়গা",
  "Helps us match the nearest NGO and guide the volunteer to you.": "কাছের এনজিওর সঙ্গে মেলাতে এবং স্বেচ্ছাসেবককে আপনার কাছে পৌঁছাতে সাহায্য করে।",
  "Contact person": "যোগাযোগের ব্যক্তি",
  "Contact phone": "যোগাযোগের ফোন",
  "Anything else?": "আর কিছু?",
  "Food photo": "খাবারের ছবি",
  "JPG, PNG or WebP up to 2 MB. Helps NGOs decide faster.": "JPG, PNG বা WebP, সর্বোচ্চ ২ MB। এনজিওকে দ্রুত সিদ্ধান্ত নিতে সাহায্য করে।",
  "e.g. Ask for the manager at the back gate. Contains nuts.": "যেমন: পেছনের গেটে ম্যানেজারকে খুঁজুন। বাদাম আছে।",
  "By posting, you confirm this food is safe to eat and stored hygienically.": "পোস্ট করে আপনি নিশ্চিত করছেন যে খাবারটি খাওয়ার উপযোগী এবং স্বাস্থ্যসম্মতভাবে রাখা।",
  "Posting donation…": "দান পোস্ট হচ্ছে…",
  "Post donation": "দান পোস্ট করুন",
  "Donation details": "দানের বিবরণ",
  "Donation posted!": "দান পোস্ট হয়েছে!",
  "We’re notifying NGOs nearby. You’ll get a notification as soon as one accepts.": "কাছের এনজিওগুলোকে জানানো হচ্ছে। কেউ গ্রহণ করলেই আপনি নোটিফিকেশন পাবেন।",
  "Paused for a food-safety check": "খাদ্য-নিরাপত্তা যাচাইয়ের জন্য স্থগিত",
  "NGOs can’t see or accept this food until FoodBridge finishes the check.": "ফুডব্রিজের যাচাই শেষ না হওয়া পর্যন্ত এনজিওগুলো এই খাবার দেখতে বা গ্রহণ করতে পারবে না।",
  "If the food isn’t safe any more, please cancel it.": "খাবারটি আর নিরাপদ না থাকলে দয়া করে বাতিল করুন।",
  "This is the remaining part of a larger donation: some of it was already allocated to an NGO.": "এটি একটি বড় দানের বাকি অংশ: কিছু অংশ আগেই একটি এনজিওকে দেওয়া হয়েছে।",
  "See the allocated part": "বরাদ্দ করা অংশ দেখুন",
  "Cancel donation": "দান বাতিল করুন",
  "Cancel this donation?": "এই দানটি বাতিল করবেন?",
  "The NGO and volunteer (if any) will be told it’s no longer available.": "এনজিও ও স্বেচ্ছাসেবককে (যদি থাকে) জানানো হবে যে এটি আর পাওয়া যাবে না।",
  "e.g. Food was already given away": "যেমন: খাবার আগেই দিয়ে দেওয়া হয়েছে",
  "Yes, cancel donation": "হ্যাঁ, দান বাতিল করুন",
  "Donation progress": "দানের অগ্রগতি",
  "Requests from NGOs": "এনজিওর অনুরোধ",
  "Accept the NGO that should receive this food. The others are told automatically.": "যে এনজিও এই খাবার পাবে তাদের অনুরোধ গ্রহণ করুন। বাকিদের স্বয়ংক্রিয়ভাবে জানানো হবে।",
  "Nearby NGOs can see your donation. Their requests will appear here.": "কাছের এনজিওগুলো আপনার দান দেখতে পাচ্ছে। তাদের অনুরোধ এখানে দেখা যাবে।",
  "Wants {qty} to feed {people}, pickup around {time}.": "{people} মানুষের জন্য {qty} চায়, সংগ্রহের সময় আনুমানিক {time}।",
  "No requests yet. We’ll notify you when an NGO asks for it.": "এখনো কোনো অনুরোধ নেই। কোনো এনজিও চাইলে আমরা আপনাকে জানাব।",
  "Waiting for an NGO to accept.": "কোনো এনজিওর গ্রহণের অপেক্ষায়।",
  "Assigned after an NGO accepts.": "এনজিও গ্রহণ করার পর নির্ধারণ করা হবে।",
  "Skip the volunteer login: play the volunteer’s part to test the flow.": "স্বেচ্ছাসেবক হিসেবে লগইন না করেই তার ভূমিকা পালন করে পুরো প্রক্রিয়াটি পরীক্ষা করুন।",
  "I am a…": "আমি একজন…",
  "Business / organisation name": "ব্যবসা / প্রতিষ্ঠানের নাম",
  "e.g. Star Kabab, Dhanmondi": "যেমন: স্টার কাবাব, ধানমন্ডি",
  "Your full name": "আপনার পুরো নাম",
  "Used as the default pickup address. You can change it per donation.": "এটি ডিফল্ট সংগ্রহের ঠিকানা হিসেবে ব্যবহৃত হবে। প্রতিটি দানে বদলাতে পারবেন।",
  "Area / city": "এলাকা / শহর",
  "e.g. Mirpur, Dhaka": "যেমন: মিরপুর, ঢাকা",
  "I will only donate food that is safe to eat, stored hygienically and within its best-before time.": "আমি শুধু খাওয়ার উপযোগী, স্বাস্থ্যসম্মতভাবে রাখা এবং খাওয়ার শেষ সময়ের মধ্যে থাকা খাবার দান করব।",
  "Create donor account": "দাতা অ্যাকাউন্ট তৈরি করুন",

  // Answering NGO food requests
  "NGO needs": "এনজিওর চাহিদা",
  "NGOs needing food": "যেসব এনজিওর খাবার দরকার",
  "NGO requests": "এনজিওর অনুরোধ",
  "Verified NGOs near you post what they need. Reply if you can help, or post the food for their request: the NGO confirms it and a volunteer collects it from you.": "আপনার কাছের যাচাই করা এনজিওগুলো জানায় তাদের কী দরকার। সাহায্য করতে পারলে সাড়া দিন, অথবা তাদের অনুরোধের জন্য খাবার পোস্ট করুন: এনজিও তা নিশ্চিত করবে আর একজন স্বেচ্ছাসেবক আপনার কাছ থেকে খাবার নিয়ে যাবেন।",
  "No open requests near you right now": "এই মুহূর্তে আপনার কাছে কোনো খোলা অনুরোধ নেই",
  "We’ll send you an alert when an NGO nearby needs food, so you don’t have to keep checking.": "কাছের কোনো এনজিওর খাবার দরকার হলে আমরা আপনাকে জানিয়ে দেব, তাই বারবার দেখে যেতে হবে না।",
  "NGOs near you need food": "আপনার কাছের এনজিওগুলোর খাবার দরকার",
  "Can you help? Reply to the NGO, or post your food for their request. They confirm it and a volunteer collects it.": "আপনি কি সাহায্য করতে পারবেন? এনজিওকে সাড়া দিন, অথবা তাদের অনুরোধের জন্য খাবার পোস্ট করুন। তারা নিশ্চিত করলে একজন স্বেচ্ছাসেবক খাবার নিয়ে যাবেন।",
  "{food} for {n} people": "{n} জনের জন্য {food}",
  "Needed {when}": "দরকার {when}",
  "Amount asked": "চাওয়া পরিমাণ",
  "Your reply": "আপনার উত্তর",
  "You posted food for this request. Follow it →": "এই অনুরোধের জন্য আপনি খাবার পোস্ট করেছেন। অবস্থা দেখুন →",
  "Send and post the food": "পাঠান ও খাবার পোস্ট করুন",
  "Only send the reply": "শুধু উত্তর পাঠান",
  "Post food for it": "এর জন্য খাবার পোস্ট করুন",
  "Your reply to the NGO": "এনজিওকে আপনার উত্তর",
  "e.g. I’ll have some food left soon. I can give this.": "যেমন: আমার এখন কিছু খাবার বেঁচে যাবে, আমি এই খাবারটা দিতে পারব।",
  "I can help": "আমি সাহায্য করতে পারব",
  "Update my reply": "উত্তর বদলান",
  "{n} donor replied": "{n} জন দাতা সাড়া দিয়েছেন",
  "{n} donors replied": "{n} জন দাতা সাড়া দিয়েছেন",
  "Sent. The NGO can see your reply.": "পাঠানো হয়েছে। এনজিও আপনার উত্তর দেখতে পাবে।",
  "Write a short reply.": "একটি ছোট উত্তর লিখুন।",
  "Keep it under 300 characters.": "৩০০ অক্ষরের মধ্যে রাখুন।",
  "For {ngo}’s request": "{ngo}-এর অনুরোধের জন্য",
  "They need {food} for {n} people in {area} by {time}. Your food is offered to them first; they confirm it, then a volunteer collects it.": "{area}-এ {time}-এর মধ্যে তাদের {n} জনের জন্য {food} দরকার। আপনার খাবার প্রথমে তাদেরই দেওয়া হবে; তারা নিশ্চিত করলে একজন স্বেচ্ছাসেবক তা নিয়ে যাবেন।",
  "See the food they posted": "তাদের পোস্ট করা খাবার দেখুন",
  "Donor replies": "দাতাদের উত্তর",
  "Donors near you who answered this request.": "আপনার কাছের যেসব দাতা এই অনুরোধে সাড়া দিয়েছেন।",
  "I posted food for this request.": "এই অনুরোধের জন্য আমি খাবার পোস্ট করেছি।",
};
