export const NGO: Record<string, string> = {
  "NGO dashboard": "এনজিওর ড্যাশবোর্ড",
  "Thanks for registering! Your NGO is under review": "নিবন্ধনের জন্য ধন্যবাদ! আপনার এনজিও যাচাই করা হচ্ছে",
  "Your NGO is under review": "আপনার এনজিও যাচাই করা হচ্ছে",
  "Our team verifies every NGO before it can request food, usually within one working day. Meanwhile you can browse donations and {link}.": "খাবারের অনুরোধ করার আগে আমাদের দল প্রতিটি এনজিও যাচাই করে, সাধারণত এক কর্মদিবসের মধ্যে। এর মধ্যে আপনি দানগুলো দেখতে পারেন এবং {link}।",
  "complete your profile": "আপনার প্রোফাইল সম্পূর্ণ করুন",
  "Serving {area}.": "{area} এলাকায় সেবা দিচ্ছে।",
  "Find surplus food nearby and get it to the people you serve.": "কাছের উদ্বৃত্ত খাবার খুঁজুন এবং আপনার সেবা নেওয়া মানুষের কাছে পৌঁছে দিন।",
  "Post a food request": "খাবারের অনুরোধ পোস্ট করুন",
  "My requests": "আমার অনুরোধ",
  "From donations you marked as distributed.": "যে দানগুলো আপনি বিতরণ সম্পন্ন হিসেবে চিহ্নিত করেছেন সেগুলো থেকে।",
  "Available donations": "পাওয়া যাচ্ছে এমন দান",
  "Open for requests right now": "এখনই অনুরোধের জন্য খোলা",
  "Active requests": "সক্রিয় অনুরোধ",
  "Pending, matched or on the way": "অপেক্ষমাণ, মিলেছে বা পথে",
  "{n} open food request": "{n}টি খোলা খাবারের অনুরোধ",
  "{n} open food requests": "{n}টি খোলা খাবারের অনুরোধ",
  "Received donations": "পাওয়া দান",
  "Delivered to your organisation": "আপনার প্রতিষ্ঠানে পৌঁছেছে",
  "Food received over time": "সময়ের সঙ্গে পাওয়া খাবার",
  "Counted when food is delivered to you.": "খাবার আপনার কাছে পৌঁছালে গোনা হয়।",
  "See your report": "আপনার রিপোর্ট দেখুন",
  "Meals received": "পাওয়া বেলার খাবার",
  "Deliveries received": "পাওয়া ডেলিভারি",
  "Meals served (all time)": "পরিবেশিত বেলার খাবার (সব সময়)",
  "Available near {area}": "{area}-এর কাছে পাওয়া যাচ্ছে",
  "Available now": "এখন পাওয়া যাচ্ছে",
  "Soonest-expiring first.": "যেগুলোর মেয়াদ আগে শেষ হবে সেগুলো আগে।",
  "No food available right now": "এখন কোনো খাবার পাওয়া যাচ্ছে না",
  "New donations appear here as soon as donors post them.": "দাতারা পোস্ট করলেই নতুন দান এখানে দেখা যাবে।",
  "Track each request from match to delivery.": "মিল থেকে ডেলিভারি পর্যন্ত প্রতিটি অনুরোধ অনুসরণ করুন।",
  "No active requests. Browse available food and request what you can serve.": "কোনো সক্রিয় অনুরোধ নেই। পাওয়া যাচ্ছে এমন খাবার দেখুন এবং যতটুকু পরিবেশন করতে পারবেন ততটুকুর অনুরোধ করুন।",
  "Food that donors have posted and nobody has claimed yet. Soonest-expiring first.": "দাতারা পোস্ট করেছেন কিন্তু এখনো কেউ নেয়নি এমন খাবার। যেগুলোর মেয়াদ আগে শেষ হবে সেগুলো আগে।",
  "Area or address, e.g. Mirpur": "এলাকা বা ঠিকানা, যেমন: মিরপুর",
  "All food types": "সব ধরনের খাবার",
  "Quick filter:": "দ্রুত ফিল্টার:",
  "My service area": "আমার সেবা এলাকা",
  "{n} donation available": "{n}টি দান পাওয়া যাচ্ছে",
  "{n} donations available": "{n}টি দান পাওয়া যাচ্ছে",
  "{n} donation available matching your filters": "আপনার ফিল্টারের সঙ্গে মেলে এমন {n}টি দান পাওয়া যাচ্ছে",
  "{n} donations available matching your filters": "আপনার ফিল্টারের সঙ্গে মেলে এমন {n}টি দান পাওয়া যাচ্ছে",
  "No donations match these filters": "এই ফিল্টারের সঙ্গে কোনো দান মেলেনি",
  "Try a wider area or a longer availability window.": "আরও বড় এলাকা বা আরও লম্বা সময়সীমা দিয়ে চেষ্টা করুন।",
  "New donations appear here as soon as donors post them. You’ll also see them on your dashboard.": "দাতারা পোস্ট করলেই নতুন দান এখানে দেখা যাবে। আপনার ড্যাশবোর্ডেও দেখতে পাবেন।",
  "Food accepted!": "খাবার গ্রহণ করা হয়েছে!",
  "It’s matched to your request. The donor has been notified and a volunteer will be assigned to bring it.": "এটি আপনার অনুরোধের সঙ্গে মিলেছে। দাতাকে জানানো হয়েছে এবং খাবার আনতে একজন স্বেচ্ছাসেবক নির্ধারণ করা হবে।",
  "Request sent!": "অনুরোধ পাঠানো হয়েছে!",
  "The donor has been notified. You’ll get a notification when they respond.": "দাতাকে জানানো হয়েছে। তিনি সাড়া দিলে আপনি নোটিফিকেশন পাবেন।",
  "Shared with you once the donor accepts your request.": "দাতা আপনার অনুরোধ গ্রহণ করলে আপনাকে জানানো হবে।",
  "Verification pending": "যাচাই বাকি",
  "You can request food once our team has verified your NGO.": "আমাদের দল আপনার এনজিও যাচাই করার পর আপনি খাবারের অনুরোধ করতে পারবেন।",
  "Request this food": "এই খাবারের অনুরোধ করুন",
  "The donor reviews requests and picks one NGO.": "দাতা অনুরোধগুলো দেখে একটি এনজিও বেছে নেন।",
  "Matched to your food request": "আপনার খাবারের অনুরোধের সঙ্গে মিলেছে",
  "View your request": "আপনার অনুরোধ দেখুন",
  "Your request": "আপনার অনুরোধ",
  "Withdraw request": "অনুরোধ প্রত্যাহার করুন",
  "Pickup & delivery": "সংগ্রহ ও ডেলিভারি",
  "A volunteer will be assigned soon.": "শীঘ্রই একজন স্বেচ্ছাসেবক নির্ধারণ করা হবে।",
  "Confirm food received": "খাবার পাওয়া নিশ্চিত করুন",
  "Quantity ({unit})": "পরিমাণ ({unit})",
  "Up to {n} available": "সর্বোচ্চ {n} পাওয়া যাচ্ছে",
  "People to feed": "কতজনকে খাওয়াবেন",
  "Preferred pickup / delivery time": "পছন্দের সংগ্রহ / ডেলিভারির সময়",
  "Must be before the food’s best-before time.": "খাবারের খাওয়ার শেষ সময়ের আগে হতে হবে।",
  "Notes for the donor": "দাতার জন্য নোট",
  "e.g. We serve dinner to 60 children at 7 PM.": "যেমন: আমরা সন্ধ্যা ৭টায় ৬০ জন শিশুকে রাতের খাবার দিই।",
  "Sending request…": "অনুরোধ পাঠানো হচ্ছে…",
  "Meals served": "পরিবেশিত বেলার খাবার",
  "Roughly how many people ate from this donation.": "এই দান থেকে আনুমানিক কতজন খেয়েছেন।",
  "Mark as distributed": "বিতরণ সম্পন্ন হিসেবে চিহ্নিত করুন",
  "Accept this food": "এই খাবার গ্রহণ করুন",
  "Reject": "প্রত্যাখ্যান করুন",
  "Rejecting…": "প্রত্যাখ্যান করা হচ্ছে…",
  "Can’t receive it? Cancel this match": "গ্রহণ করতে পারছেন না? মিলটি বাতিল করুন",
  "e.g. Our kitchen is closed tonight": "যেমন: আজ রাতে আমাদের রান্নাঘর বন্ধ",
  "Cancel match": "মিল বাতিল করুন",
  "Possible until the volunteer picks the food up. The donor and volunteer are told straight away.": "স্বেচ্ছাসেবক খাবার সংগ্রহ করার আগ পর্যন্ত সম্ভব। দাতা ও স্বেচ্ছাসেবককে সঙ্গে সঙ্গে জানানো হয়।",
  "Tell us what you need. We match available food to it, and you confirm.": "আপনার কী দরকার জানান। আমরা পাওয়া যাচ্ছে এমন খাবার মিলিয়ে দেব, আর আপনি নিশ্চিত করবেন।",
  "New request": "নতুন অনুরোধ",
  "You can post food requests once our team has verified your NGO.": "আমাদের দল আপনার এনজিও যাচাই করার পর আপনি খাবারের অনুরোধ পোস্ট করতে পারবেন।",
  "Meals requested": "অনুরোধ করা বেলার খাবার",
  "Still needed": "এখনো দরকার",
  "Filter requests": "অনুরোধ ফিল্টার করুন",
  "No food requests yet": "এখনো কোনো খাবারের অনুরোধ নেই",
  "No requests at this stage: {stage}": "এই ধাপে কোনো অনুরোধ নেই: {stage}",
  "Post what you need: food type, quantity, people and time. We’ll match available donations to it.": "আপনার প্রয়োজন পোস্ট করুন: খাবারের ধরন, পরিমাণ, মানুষের সংখ্যা ও সময়। আমরা পাওয়া যাচ্ছে এমন দান মিলিয়ে দেব।",
  "Donations you asked for": "আপনার চাওয়া দান",
  "Food you requested directly from Find food.": "“খাবার খুঁজুন” থেকে সরাসরি অনুরোধ করা খাবার।",
  "None yet. Browse Find food to request a specific donation.": "এখনো নেই। নির্দিষ্ট দানের অনুরোধ করতে “খাবার খুঁজুন” দেখুন।",
  "Distribution records": "বিতরণের রেকর্ড",
  "Donations you received and served.": "আপনার পাওয়া ও পরিবেশন করা দান।",
  "Donations you mark as distributed appear here.": "যে দানগুলো বিতরণ সম্পন্ন হিসেবে চিহ্নিত করবেন সেগুলো এখানে দেখা যাবে।",
  "New food request": "নতুন খাবারের অনুরোধ",
  "What food do you need?": "আপনার কী খাবার দরকার?",
  "We’ll match available donations by food type, quantity, location and freshness. You confirm before anything is sent.": "খাবারের ধরন, পরিমাণ, অবস্থান ও সতেজতা অনুযায়ী আমরা দান মিলিয়ে দেব। কিছু পাঠানোর আগে আপনি নিশ্চিত করবেন।",
  "Post request": "অনুরোধ পোস্ট করুন",
  "Edit food request": "খাবারের অনুরোধ সম্পাদনা",
  "Back to request": "অনুরোধে ফিরুন",
  "Edit request": "অনুরোধ সম্পাদনা",
  "Update what you need": "আপনার প্রয়োজন হালনাগাদ করুন",
  "Saving withdraws any match waiting for you and looks again.": "সংরক্ষণ করলে আপনার জন্য অপেক্ষমাণ মিল প্রত্যাহার হবে এবং আবার খোঁজা হবে।",
  "Please check every field before posting.": "পোস্ট করার আগে প্রতিটি ঘর যাচাই করুন।",
  "Choose “Any food” to be matched with anything suitable.": "উপযুক্ত যেকোনো খাবারের সঙ্গে মেলাতে “যেকোনো খাবার” বেছে নিন।",
  "Description": "বিবরণ",
  "e.g. Rice and curry for dinner": "যেমন: রাতের খাবারের জন্য ভাত-তরকারি",
  "Quantity needed": "প্রয়োজনীয় পরিমাণ",
  "People to serve": "কতজনকে খাওয়াবেন",
  "Estimated meals needed.": "আনুমানিক কত বেলার খাবার দরকার।",
  "Service area": "সেবা এলাকা",
  "Delivery address": "ডেলিভারির ঠিকানা",
  "Delivery location on the map": "মানচিত্রে ডেলিভারির অবস্থান",
  "Used to match the nearest food and guide the volunteer. Defaults to your organisation’s pin.": "সবচেয়ে কাছের খাবার মেলাতে ও স্বেচ্ছাসেবককে পথ দেখাতে ব্যবহৃত হয়। না দিলে আপনার প্রতিষ্ঠানের পিন ধরা হবে।",
  "Needed by": "কখনের মধ্যে দরকার",
  "We match food that can be picked up before this time.": "এই সময়ের আগে সংগ্রহ করা যায় এমন খাবার আমরা মিলিয়ে দিই।",
  "e.g. Children’s dinner at 7 PM, no beef please.": "যেমন: সন্ধ্যা ৭টায় শিশুদের রাতের খাবার, গরুর মাংস নয়।",
  "Don’t include names or personal details of the people you serve.": "যাদের সেবা দেন তাদের নাম বা ব্যক্তিগত তথ্য লিখবেন না।",
  "Food request": "খাবারের অনুরোধ",
  "Request posted": "অনুরোধ পোস্ট হয়েছে",
  "We already found a match. Review it below.": "আমরা ইতিমধ্যে একটি মিল পেয়েছি। নিচে দেখে নিন।",
  "We’ll notify you as soon as suitable food is available.": "উপযুক্ত খাবার পাওয়া গেলেই আমরা আপনাকে জানাব।",
  "Request updated.": "অনুরোধ হালনাগাদ হয়েছে।",
  "We found a match": "আমরা একটি মিল পেয়েছি",
  "{qty} for you (~{n} meals)": "আপনার জন্য {qty} (~{n} বেলার খাবার)",
  "Why this match:": "কেন এই মিল:",
  "The rest stays available for other NGOs.": "বাকিটা অন্য এনজিওগুলোর জন্য খোলা থাকবে।",
  "Food for this request": "এই অনুরোধের খাবার",
  "Accepted donations and their delivery progress.": "গৃহীত দান ও সেগুলোর ডেলিভারির অগ্রগতি।",
  "Nothing matched yet. We check again whenever new food is posted.": "এখনো কিছু মেলেনি। নতুন খাবার পোস্ট হলেই আমরা আবার খুঁজি।",
  "No food was accepted for this request.": "এই অনুরোধের জন্য কোনো খাবার গ্রহণ করা হয়নি।",
  "Matching history": "মেলানোর ইতিহাস",
  "Every donation proposed, accepted, rejected or allocated for this request.": "এই অনুরোধের জন্য প্রস্তাবিত, গৃহীত, প্রত্যাখ্যাত বা বরাদ্দ করা প্রতিটি দান।",
  "Request details": "অনুরোধের বিবরণ",
  "Your organisation’s address": "আপনার প্রতিষ্ঠানের ঠিকানা",
  "Pinned on the map": "মানচিত্রে পিন করা",
  "No map pin (your profile pin is used)": "মানচিত্রে পিন নেই (আপনার প্রোফাইলের পিন ব্যবহার হবে)",
  "Cancel request": "অনুরোধ বাতিল করুন",
  "We have enough — stop matching": "আমাদের যথেষ্ট আছে — মেলানো বন্ধ করুন",
  "Food has been accepted for this request, so it can no longer be edited or cancelled.": "এই অনুরোধের জন্য খাবার গ্রহণ করা হয়েছে, তাই এটি আর সম্পাদনা বা বাতিল করা যাবে না।",
  "Organisation": "প্রতিষ্ঠান",
  "Organisation name": "প্রতিষ্ঠানের নাম",
  "Registration no.": "নিবন্ধন নম্বর",
  "NGO Affairs Bureau / Social Welfare no.": "এনজিও বিষয়ক ব্যুরো / সমাজসেবা অধিদপ্তরের নম্বর",
  "Where food is usually delivered.": "সাধারণত যেখানে খাবার পৌঁছানো হয়।",
  "People served per day": "প্রতিদিন কতজনকে সেবা দেন",
  "We will handle donated food hygienically, serve it promptly and never sell it.": "আমরা দানের খাবার স্বাস্থ্যসম্মতভাবে রাখব, দ্রুত পরিবেশন করব এবং কখনো বিক্রি করব না।",
  "Create NGO account": "এনজিও অ্যাকাউন্ট তৈরি করুন",
  "Used to show nearby food first.": "কাছের খাবার আগে দেখাতে ব্যবহৃত হয়।",
  "About your organisation": "আপনার প্রতিষ্ঠান সম্পর্কে",
  "Who you serve, meal times, storage (fridge, freezer)…": "কাদের সেবা দেন, খাবারের সময়, সংরক্ষণ ব্যবস্থা (ফ্রিজ, ফ্রিজার)…",
  "Delivery point on the map": "মানচিত্রে ডেলিভারির জায়গা",
  "Where volunteers bring food. Used to match the nearest donations first.": "স্বেচ্ছাসেবকেরা যেখানে খাবার আনেন। সবচেয়ে কাছের দান আগে মেলাতে ব্যবহৃত হয়।",
};
