export const NOTIFICATIONS: Record<string, string> = {
  "Your donation “{food}” is live. We’re letting nearby NGOs know.": "আপনার দান “{food}” এখন সক্রিয়। কাছের এনজিওগুলোকে জানানো হচ্ছে।",
  "“{food}” is allocated to an NGO. We’re assigning the nearest volunteer.": "“{food}” একটি এনজিওকে বরাদ্দ করা হয়েছে। সবচেয়ে কাছের স্বেচ্ছাসেবক নির্ধারণ করা হচ্ছে।",
  "A volunteer accepted the pickup of “{food}”.": "একজন স্বেচ্ছাসেবক “{food}” সংগ্রহের কাজ নিয়েছেন।",
  "“{food}” has been picked up and is on its way.": "“{food}” সংগ্রহ করা হয়েছে এবং পথে আছে।",
  "“{food}” was delivered to the NGO.": "“{food}” এনজিওর কাছে পৌঁছে দেওয়া হয়েছে।",
  "“{food}” reached people in need. Thank you for donating!": "“{food}” প্রয়োজনে থাকা মানুষের কাছে পৌঁছেছে। দান করার জন্য ধন্যবাদ!",
  "You cancelled “{food}”.": "আপনি “{food}” বাতিল করেছেন।",
  "“{food}” expired before pickup.": "সংগ্রহের আগেই “{food}”-এর মেয়াদ শেষ হয়েছে।",
  "“{food}” was picked up from the donor.": "দাতার কাছ থেকে “{food}” সংগ্রহ করা হয়েছে।",
  "“{food}” is on the way to you. You can follow it on the map.": "“{food}” আপনার দিকে আসছে। মানচিত্রে অনুসরণ করতে পারেন।",
  "“{food}” was delivered. Mark it distributed once it’s served.": "“{food}” পৌঁছেছে। পরিবেশনের পর বিতরণ সম্পন্ন হিসেবে চিহ্নিত করুন।",
  "The donor cancelled “{food}”.": "দাতা “{food}” বাতিল করেছেন।",
  "“{food}” expired before it could be picked up.": "সংগ্রহের আগেই “{food}”-এর মেয়াদ শেষ হয়েছে।",
  "You accepted the pickup of “{food}”. Head to the donor at pickup time.": "আপনি “{food}” সংগ্রহের কাজ নিয়েছেন। সংগ্রহের সময়ে দাতার কাছে যান।",
  "Pickup confirmed for “{food}”. Deliver it to the NGO.": "“{food}”-এর সংগ্রহ নিশ্চিত হয়েছে। এটি এনজিওর কাছে পৌঁছে দিন।",
  "Delivery completed for “{food}”. Thank you for volunteering!": "“{food}”-এর ডেলিভারি সম্পন্ন। স্বেচ্ছাসেবার জন্য ধন্যবাদ!",
  "The donor cancelled “{food}”. No pickup needed.": "দাতা “{food}” বাতিল করেছেন। সংগ্রহের দরকার নেই।",
  "“{food}” expired before pickup. The task is closed.": "সংগ্রহের আগেই “{food}”-এর মেয়াদ শেষ হয়েছে। কাজটি বন্ধ।",
  "You handed back the pickup of “{food}”. Thanks for letting us know.": "আপনি “{food}” সংগ্রহের কাজ ফেরত দিয়েছেন। জানানোর জন্য ধন্যবাদ।",
  "You’ve been taken off the pickup of “{food}”. No need to collect it.": "আপনাকে “{food}” সংগ্রহের কাজ থেকে সরানো হয়েছে। এটি সংগ্রহ করার দরকার নেই।",
  "The volunteer for “{food}” changed. We’re assigning another one.": "“{food}”-এর স্বেচ্ছাসেবক বদলেছে। আরেকজনকে নির্ধারণ করা হচ্ছে।",
  "{by} cancelled the match for “{food}”. It’s available again.": "{by} “{food}”-এর মিল বাতিল করেছে। এটি আবার পাওয়া যাচ্ছে।",
  "The NGO": "এনজিও",
  "FoodBridge": "ফুডব্রিজ",
  "FoodBridge cancelled your match for “{food}”.": "ফুডব্রিজ “{food}”-এর জন্য আপনার মিল বাতিল করেছে।",
  "“{food}” no longer needs a pickup. The match was cancelled.": "“{food}” আর সংগ্রহের দরকার নেই। মিলটি বাতিল হয়েছে।",
  "FoodBridge cancelled your donation “{food}”.": "ফুডব্রিজ আপনার দান “{food}” বাতিল করেছে।",
  "FoodBridge cancelled “{food}”. It won’t be delivered.": "ফুডব্রিজ “{food}” বাতিল করেছে। এটি পৌঁছানো হবে না।",
  "FoodBridge cancelled “{food}”. No pickup needed.": "ফুডব্রিজ “{food}” বাতিল করেছে। সংগ্রহের দরকার নেই।",
  "“{food}” is no longer available. It was cancelled.": "“{food}” আর পাওয়া যাচ্ছে না। এটি বাতিল হয়েছে।",
  "“{food}” went to another NGO this time.": "এবার “{food}” অন্য একটি এনজিওর কাছে গেছে।",
  "Request sent for “{food}”. We’ll tell you when the donor responds.": "“{food}”-এর জন্য অনুরোধ পাঠানো হয়েছে। দাতা সাড়া দিলে আমরা জানাব।",
  "{ngo} requested “{food}” to feed {n} people. Review and accept it.": "{ngo} {n} জনকে খাওয়াতে “{food}” চেয়েছে। দেখে নিয়ে গ্রহণ করুন।",
  "The donor accepted your request for “{food}”.": "দাতা “{food}”-এর জন্য আপনার অনুরোধ গ্রহণ করেছেন।",
  "The donor couldn’t accept your request for “{food}”.": "দাতা “{food}”-এর জন্য আপনার অনুরোধ গ্রহণ করতে পারেননি।",
  "We found food for your request: “{food}” from {donor} (~{n} meals, {away} away). Accept or reject it.": "আপনার অনুরোধের জন্য খাবার পাওয়া গেছে: {donor}-এর “{food}” (~{n} বেলার খাবার, {away} দূরে)। গ্রহণ বা প্রত্যাখ্যান করুন।",
  "We found food for your request: “{food}” from {donor} (~{n} meals). Accept or reject it.": "আপনার অনুরোধের জন্য খাবার পাওয়া গেছে: {donor}-এর “{food}” (~{n} বেলার খাবার)। গ্রহণ বা প্রত্যাখ্যান করুন।",
  "{keep} {unit} of “{food}” went to {ngo}. The other {rest} {unit2} are still available for other NGOs.": "“{food}”-এর {keep} {unit} {ngo}-এর কাছে গেছে। বাকি {rest} {unit2} অন্য এনজিওগুলোর জন্য এখনো পাওয়া যাচ্ছে।",
  "New task assigned to you: pick up “{food}” ({away} away) and take it to {ngo}. Please accept or decline within {n} minutes.": "আপনাকে নতুন কাজ দেওয়া হয়েছে: “{food}” সংগ্রহ করুন ({away} দূরে) এবং {ngo}-এর কাছে পৌঁছে দিন। {n} মিনিটের মধ্যে গ্রহণ বা প্রত্যাখ্যান করুন।",
  "New task assigned to you: pick up “{food}” and take it to {ngo}. Please accept or decline within {n} minutes.": "আপনাকে নতুন কাজ দেওয়া হয়েছে: “{food}” সংগ্রহ করে {ngo}-এর কাছে পৌঁছে দিন। {n} মিনিটের মধ্যে গ্রহণ বা প্রত্যাখ্যান করুন।",
  "the NGO": "এনজিও",
  "No nearby volunteer accepted the pickup of “{food}”. It’s now open to every volunteer.": "কাছের কোনো স্বেচ্ছাসেবক “{food}” সংগ্রহের কাজ নেননি। এখন এটি সব স্বেচ্ছাসেবকের জন্য খোলা।",
  "Open pickup: “{food}” still needs a volunteer. Accept it if you can help.": "খোলা সংগ্রহের কাজ: “{food}”-এর জন্য এখনো স্বেচ্ছাসেবক দরকার। সাহায্য করতে পারলে গ্রহণ করুন।",
  "A pickup offered to you was passed to another volunteer because there was no reply in {n} minutes.": "{n} মিনিটের মধ্যে উত্তর না পাওয়ায় আপনাকে দেওয়া সংগ্রহের কাজটি অন্য স্বেচ্ছাসেবকের কাছে দেওয়া হয়েছে।",
  "FoodBridge has asked you to pick up “{food}”. Please accept or decline within {n} minutes.": "ফুডব্রিজ আপনাকে “{food}” সংগ্রহ করতে অনুরোধ করেছে। {n} মিনিটের মধ্যে গ্রহণ বা প্রত্যাখ্যান করুন।",
  "Pickup reminder: collect “{food}” from {address} soon.": "সংগ্রহের অনুস্মারক: শীঘ্রই {address} থেকে “{food}” সংগ্রহ করুন।",
  "FoodBridge accepted a food match for your request. A volunteer will bring it.": "ফুডব্রিজ আপনার অনুরোধের জন্য একটি খাবারের মিল গ্রহণ করেছে। একজন স্বেচ্ছাসেবক তা নিয়ে আসবেন।",
  "FoodBridge withdrew a food match for your request. We’ll look for another one.": "ফুডব্রিজ আপনার অনুরোধের একটি খাবারের মিল প্রত্যাহার করেছে। আমরা আরেকটি খুঁজব।",
  "Your NGO is verified. You can now request food.": "আপনার এনজিও যাচাই করা হয়েছে। এখন আপনি খাবারের অনুরোধ করতে পারবেন।",
  "You’re verified! Switch to Available to start receiving pickups.": "আপনি যাচাইকৃত! সংগ্রহের কাজ পেতে “ফাঁকা আছি” চালু করুন।",
  "FoodBridge withdrew one of your requests. Contact support if this is unexpected.": "ফুডব্রিজ আপনার একটি অনুরোধ প্রত্যাহার করেছে। অপ্রত্যাশিত মনে হলে সহায়তা দলের সঙ্গে যোগাযোগ করুন।",
  "FoodBridge cancelled one of your food requests.": "ফুডব্রিজ আপনার একটি খাবারের অনুরোধ বাতিল করেছে।",
  "A match for “{food}” was withdrawn for a food-safety check. We’ll find you other food.": "খাদ্য-নিরাপত্তা যাচাইয়ের জন্য “{food}”-এর একটি মিল প্রত্যাহার করা হয়েছে। আমরা আপনার জন্য অন্য খাবার খুঁজব।",
  "FoodBridge paused “{food}” for a food-safety check.": "খাদ্য-নিরাপত্তা যাচাইয়ের জন্য ফুডব্রিজ “{food}” স্থগিত করেছে।",
  "Reply to support or cancel it if the food isn’t safe.": "খাবার নিরাপদ না হলে সহায়তা দলকে জানান বা বাতিল করুন।",
  "The safety check for “{food}” is done. It’s available to NGOs again.": "“{food}”-এর নিরাপত্তা যাচাই শেষ। এটি আবার এনজিওগুলোর জন্য পাওয়া যাচ্ছে।",
  "“{food}” expires in {n} min and hasn’t been picked up yet.": "“{food}”-এর মেয়াদ {n} মিনিটে শেষ হবে, এখনো সংগ্রহ করা হয়নি।",
  "“{food}” (on its way to you) expires in {n} min.": "“{food}” (আপনার দিকে আসছে)-এর মেয়াদ {n} মিনিটে শেষ হবে।",
  "“{food}”, which you’re waiting on, expires in {n} min.": "আপনি যে “{food}”-এর অপেক্ষায় আছেন তার মেয়াদ {n} মিনিটে শেষ হবে।",
  "Hurry: “{food}” expires in {n} min. Pick it up as soon as you can.": "তাড়াতাড়ি করুন: “{food}”-এর মেয়াদ {n} মিনিটে শেষ হবে। যত দ্রুত সম্ভব সংগ্রহ করুন।",
  "Allocated food “{food}” expires in {n} min and hasn’t been collected yet.": "বরাদ্দ করা খাবার “{food}”-এর মেয়াদ {n} মিনিটে শেষ হবে, এখনো সংগ্রহ করা হয়নি।",
  "Offered by FoodBridge": "ফুডব্রিজ প্রস্তাব দিয়েছে",

  // Donors answering NGO food requests
  "{ngo} needs {food} for {n} people in {area}. Can you help?": "{area}-এ {ngo}-এর {n} জনের জন্য {food} দরকার। আপনি কি সাহায্য করতে পারবেন?",
  "{donor} replied to your request “{food}”: “{message}”": "{donor} আপনার অনুরোধ “{food}”-এ সাড়া দিয়েছেন: “{message}”",
  "{donor} posted food for your request: “{food}” (~{n} meals). Accept or reject it.": "{donor} আপনার অনুরোধের জন্য খাবার পোস্ট করেছেন: “{food}” (~{n} বেলার খাবার)। গ্রহণ বা প্রত্যাখ্যান করুন।",
};
