export const VOLUNTEER: Record<string, string> = {
  "Volunteer dashboard": "স্বেচ্ছাসেবকের ড্যাশবোর্ড",
  "Thanks for signing up! Your account is under review": "যোগ দেওয়ার জন্য ধন্যবাদ! আপনার অ্যাকাউন্ট যাচাই করা হচ্ছে",
  "Your account is under review": "আপনার অ্যাকাউন্ট যাচাই করা হচ্ছে",
  "Our team verifies every volunteer before they see pickup addresses, usually within one working day. Meanwhile, {link}.": "সংগ্রহের ঠিকানা দেখার আগে আমাদের দল প্রতিটি স্বেচ্ছাসেবককে যাচাই করে, সাধারণত এক কর্মদিবসের মধ্যে। এর মধ্যে {link}।",
  "Task declined. We’ve offered it to the next nearest volunteer.": "কাজটি প্রত্যাখ্যান করা হয়েছে। পরের সবচেয়ে কাছের স্বেচ্ছাসেবককে প্রস্তাব দেওয়া হয়েছে।",
  "Task handed back. Thanks for letting us know; another volunteer will take it.": "কাজটি ফেরত দেওয়া হয়েছে। জানানোর জন্য ধন্যবাদ; অন্য একজন স্বেচ্ছাসেবক এটি নেবেন।",
  "Covering {area}.": "{area} এলাকায় কাজ করছেন।",
  "Pick up surplus food and bring it to NGOs.": "উদ্বৃত্ত খাবার সংগ্রহ করে এনজিওর কাছে পৌঁছে দিন।",
  "Active tasks": "সক্রিয় কাজ",
  "Meals delivered": "পৌঁছানো বেলার খাবার",
  "Current tasks": "চলমান কাজ",
  "All tasks": "সব কাজ",
  "No active tasks": "কোনো সক্রিয় কাজ নেই",
  "Accept a new pickup below to get started.": "শুরু করতে নিচে থেকে একটি নতুন সংগ্রহের কাজ নিন।",
  "Tasks you accept will appear here.": "আপনার নেওয়া কাজগুলো এখানে দেখা যাবে।",
  "You’re the nearest available volunteer. Accept or decline soon.": "আপনিই সবচেয়ে কাছের ফাঁকা স্বেচ্ছাসেবক। দ্রুত গ্রহণ বা প্রত্যাখ্যান করুন।",
  "Open pickups": "খোলা সংগ্রহের কাজ",
  "No one nearby has taken these yet. Nearest first.": "কাছাকাছি কেউ এখনো এগুলো নেননি। সবচেয়ে কাছেরটি আগে।",
  "You’re unavailable": "আপনি এখন ব্যস্ত হিসেবে আছেন",
  "Switch to Available to see and accept new pickups.": "নতুন সংগ্রহের কাজ দেখতে ও নিতে “ফাঁকা আছি” চালু করুন।",
  "No new pickups right now": "এখন নতুন কোনো সংগ্রহের কাজ নেই",
  "We’ll notify you as soon as one is ready.": "কাজ তৈরি হলেই আমরা আপনাকে জানাব।",
  "Your deliveries over time": "সময়ের সঙ্গে আপনার ডেলিভারি",
  "Deliveries completed": "সম্পন্ন ডেলিভারি",
  "Pick up from": "যেখান থেকে সংগ্রহ",
  "Deliver to": "যেখানে পৌঁছাতে হবে",
  "{d} ride": "{d} পথ",
  "Updated {time}": "হালনাগাদ {time}",
  "Available for tasks": "কাজের জন্য ফাঁকা আছি",
  "Unavailable": "ব্যস্ত",
  "Go offline": "অফলাইনে যান",
  "Go online": "অনলাইনে আসুন",
  "Pickups you’ve accepted, and your delivery history.": "আপনার নেওয়া সংগ্রহের কাজ এবং ডেলিভারির ইতিহাস।",
  "Current": "চলমান",
  "Nothing in progress": "চলমান কিছু নেই",
  "Accept a new pickup from your dashboard.": "আপনার ড্যাশবোর্ড থেকে একটি নতুন সংগ্রহের কাজ নিন।",
  "No deliveries yet": "এখনো কোনো ডেলিভারি নেই",
  "Finished deliveries will be listed here.": "শেষ হওয়া ডেলিভারিগুলো এখানে তালিকাভুক্ত হবে।",
  "Task": "কাজ",
  "This task is no longer available": "এই কাজটি আর পাওয়া যাচ্ছে না",
  "It may have gone to another volunteer, or the donation was cancelled or expired.": "এটি হয়তো অন্য স্বেচ্ছাসেবকের কাছে গেছে, অথবা দানটি বাতিল বা মেয়াদোত্তীর্ণ হয়েছে।",
  "You (saved location)": "আপনি (সংরক্ষিত অবস্থান)",
  "Task accepted!": "কাজটি নেওয়া হয়েছে!",
  "The donor and NGO have been notified. Head to the pickup address at the pickup time.": "দাতা ও এনজিওকে জানানো হয়েছে। সংগ্রহের সময়ে সংগ্রহের ঠিকানায় যান।",
  "pickup {time}": "সংগ্রহ {time}",
  "Please reply by {time} ({relative}). After that it goes to the next volunteer.": "অনুগ্রহ করে {time}-এর মধ্যে ({relative}) উত্তর দিন। এরপর এটি পরের স্বেচ্ছাসেবকের কাছে যাবে।",
  "Decline this pickup?": "এই সংগ্রহের কাজটি প্রত্যাখ্যান করবেন?",
  "It goes straight to the next nearest volunteer.": "এটি সরাসরি পরের সবচেয়ে কাছের স্বেচ্ছাসেবকের কাছে যাবে।",
  "e.g. Too far from me right now": "যেমন: এখন আমার থেকে অনেক দূরে",
  "Declining…": "প্রত্যাখ্যান করা হচ্ছে…",
  "Decline task": "কাজ প্রত্যাখ্যান করুন",
  "Switch to Available on your dashboard to accept tasks.": "কাজ নিতে ড্যাশবোর্ডে “ফাঁকা আছি” চালু করুন।",
  "You can accept tasks once your account is verified.": "অ্যাকাউন্ট যাচাই হলে আপনি কাজ নিতে পারবেন।",
  "Confirm pickup": "সংগ্রহ নিশ্চিত করুন",
  "e.g. Collected 20 plates, sealed containers.": "যেমন: ২০ প্লেট সংগ্রহ করেছি, পাত্র সিল করা।",
  "Can’t make it?": "যেতে পারছেন না?",
  "Hand this task back?": "এই কাজটি ফেরত দেবেন?",
  "We’ll offer it to the next nearest volunteer and tell the donor and NGO.": "আমরা এটি পরের সবচেয়ে কাছের স্বেচ্ছাসেবককে দেব এবং দাতা ও এনজিওকে জানাব।",
  "e.g. Bike broke down": "যেমন: সাইকেল নষ্ট হয়ে গেছে",
  "Handing back…": "ফেরত দেওয়া হচ্ছে…",
  "Hand back task": "কাজ ফেরত দিন",
  "Start delivery · I’m on my way": "ডেলিভারি শুরু · আমি রওনা দিয়েছি",
  "Already at the NGO? Confirm delivery": "ইতিমধ্যে এনজিওতে পৌঁছেছেন? ডেলিভারি নিশ্চিত করুন",
  "Confirm delivery": "ডেলিভারি নিশ্চিত করুন",
  "e.g. Handed over to the kitchen manager.": "যেমন: রান্নাঘরের ব্যবস্থাপকের হাতে দিয়েছি।",
  "Delivery task": "ডেলিভারির কাজ",
  "What to carry, where from, where to, and by when.": "কী নিতে হবে, কোথা থেকে, কোথায় এবং কখনের মধ্যে।",
  "Map & route": "মানচিত্র ও পথ",
  "You → donor → NGO. Distances are straight-line estimates.": "আপনি → দাতা → এনজিও। দূরত্বগুলো সরলরেখায় আনুমানিক।",
  "You → pickup": "আপনি → সংগ্রহ",
  "Pickup → NGO": "সংগ্রহ → এনজিও",
  "Exact pins aren’t set yet; use the addresses below.": "সঠিক পিন এখনো দেওয়া হয়নি; নিচের ঠিকানা ব্যবহার করুন।",
  "Preview route in Google Maps": "গুগল ম্যাপে পথ দেখুন",
  "Contact shared after you accept.": "কাজ নেওয়ার পর যোগাযোগের তথ্য দেখানো হবে।",
  "Confirmations": "নিশ্চিতকরণ",
  "Started delivery": "ডেলিভারি শুরু হয়েছে",
  "Donors and NGOs call this number during a pickup.": "সংগ্রহের সময় দাতা ও এনজিও এই নম্বরে ফোন করবেন।",
  "Area you can cover": "যে এলাকায় কাজ করতে পারবেন",
  "e.g. Dhanmondi, Dhaka": "যেমন: ধানমন্ডি, ঢাকা",
  "I will carry food hygienically, deliver it promptly and never sell or keep it.": "আমি স্বাস্থ্যসম্মতভাবে খাবার বহন করব, দ্রুত পৌঁছে দেব এবং কখনো বিক্রি বা নিজের কাছে রাখব না।",
  "Create volunteer account": "স্বেচ্ছাসেবক অ্যাকাউন্ট তৈরি করুন",
  "Home base / address": "বাসস্থান / ঠিকানা",
  "About you": "আপনার সম্পর্কে",
  "e.g. I have a motorbike and I’m free most evenings.": "যেমন: আমার একটি মোটরসাইকেল আছে এবং বেশিরভাগ সন্ধ্যায় সময় পাই।",
  "Home base on the map": "মানচিত্রে আপনার বাসস্থান",
  "Pickups near here are offered to you first. You can also update it from your dashboard when you’re out.": "এর কাছাকাছি সংগ্রহের কাজ আগে আপনাকে দেওয়া হয়। বাইরে থাকলে ড্যাশবোর্ড থেকেও এটি হালনাগাদ করতে পারেন।",
  "Accept task": "কাজ গ্রহণ করুন",
};
